const { Schema } = require("mongoose");

module.exports = (connection) => {
  if (connection.models.Fee) return connection.models.Fee;

  const FeeSchema = new Schema(
    {
      student: {
        type: Schema.Types.ObjectId,
        ref: "Student",
        required: true,
        index: true,
      },

      classGroup: {
        type: Schema.Types.ObjectId,
        ref: "Class",
        default: null,
        index: true,
      },

      academicYear: {
        type: String,
        default: "",
        trim: true,
        index: true,
      },

      term: {
        type: Number,
        default: 1,
        min: 1,
        max: 3,
        index: true,
      },

      title: {
        type: String,
        default: "School Fees",
        trim: true,
        maxlength: 160,
      },

      autoGenerated: {
        type: Boolean,
        default: true,
        index: true,
      },

      items: [
        {
          title: { type: String, trim: true, required: true },
          category: { type: String, trim: true, default: "Other" },
          amount: { type: Number, default: 0, min: 0 },
          required: { type: Boolean, default: true },
          note: { type: String, trim: true, default: "" },
        },
      ],

      subtotal: {
        type: Number,
        default: 0,
        min: 0,
      },

      discount: {
        type: Number,
        default: 0,
        min: 0,
      },

      totalAmount: {
        type: Number,
        default: 0,
        min: 0,
      },

      amountPaid: {
        type: Number,
        default: 0,
        min: 0,
      },

      balance: {
        type: Number,
        default: 0,
        min: 0,
      },

      status: {
        type: String,
        enum: ["draft", "issued", "partial", "paid", "void"],
        default: "draft",
        index: true,
      },

      issueNumber: {
        type: String,
        default: "",
        trim: true,
        index: true,
      },

      issuedAt: {
        type: Date,
        default: null,
      },

      dueDate: {
        type: Date,
        default: null,
      },

      notes: {
        type: String,
        default: "",
        trim: true,
        maxlength: 1000,
      },

      snapshot: {
        type: Schema.Types.Mixed,
        default: null,
      },

      snapshotHash: {
        type: String,
        default: "",
        trim: true,
      },

      createdBy: {
        type: Schema.Types.ObjectId,
        ref: "User",
        default: null,
      },

      updatedBy: {
        type: Schema.Types.ObjectId,
        ref: "User",
        default: null,
      },
    },
    { timestamps: true }
  );

  FeeSchema.pre("validate", function (next) {
    const subtotal = Array.isArray(this.items)
      ? this.items.reduce((sum, item) => sum + Number(item.amount || 0), 0)
      : 0;

    const discount = Math.max(0, Number(this.discount || 0));
    const totalAmount = Math.max(0, subtotal - discount);
    const amountPaid = Math.max(0, Number(this.amountPaid || 0));
    const balance = Math.max(0, totalAmount - amountPaid);

    this.subtotal = subtotal;
    this.totalAmount = totalAmount;
    this.balance = balance;

    if (this.status !== "void") {
      if (balance <= 0 && totalAmount > 0) this.status = "paid";
      else if (amountPaid > 0 && balance > 0) this.status = "partial";
    }

    next();
  });

  FeeSchema.index({ student: 1, academicYear: 1, term: 1 });
  FeeSchema.index({ classGroup: 1, academicYear: 1, term: 1 });
  FeeSchema.index({ status: 1, createdAt: -1 });

  return connection.model("Fee", FeeSchema);
};