const { Schema } = require("mongoose");

module.exports = (connection) => {
  if (connection.models.Transcript) return connection.models.Transcript;

  const TranscriptSchema = new Schema(
    {
      student: {
        type: Schema.Types.ObjectId,
        ref: "Student",
        required: true,
        index: true,
      },

      classGroup: {
        type: Schema.Types.ObjectId,
        ref: "Class",
        default: null,
        index: true,
      },

      kind: {
        type: String,
        enum: ["official", "unofficial"],
        default: "official",
        index: true,
      },

      rangeMode: {
        type: String,
        enum: ["auto", "current_term", "all_available", "custom"],
        default: "auto",
        index: true,
      },

      academicYearFrom: {
        type: String,
        default: "",
        trim: true,
        index: true,
      },

      academicYearTo: {
        type: String,
        default: "",
        trim: true,
        index: true,
      },

      termFrom: {
        type: Number,
        default: 1,
        min: 1,
        max: 3,
      },

      termTo: {
        type: Number,
        default: 3,
        min: 1,
        max: 3,
      },

      includeDraftResults: {
        type: Boolean,
        default: false,
      },

      autoGenerated: {
        type: Boolean,
        default: true,
        index: true,
      },

      notes: {
        type: String,
        default: "",
        trim: true,
        maxlength: 1000,
      },

      teacherComment: {
        type: String,
        default: "",
        trim: true,
        maxlength: 1000,
      },

      headTeacherComment: {
        type: String,
        default: "",
        trim: true,
        maxlength: 1000,
      },

      status: {
        type: String,
        enum: ["draft", "issued", "revoked"],
        default: "draft",
        index: true,
      },

      issueNumber: {
        type: String,
        default: "",
        trim: true,
        index: true,
      },

      issuedAt: {
        type: Date,
        default: null,
      },

      issuedBy: {
        type: Schema.Types.ObjectId,
        ref: "User",
        default: null,
      },

      revokedAt: {
        type: Date,
        default: null,
      },

      revokedBy: {
        type: Schema.Types.ObjectId,
        ref: "User",
        default: null,
      },

      revokeReason: {
        type: String,
        default: "",
        trim: true,
        maxlength: 300,
      },

      snapshot: {
        type: Schema.Types.Mixed,
        default: null,
      },

      snapshotHash: {
        type: String,
        default: "",
        trim: true,
      },

      generatedAt: {
        type: Date,
        default: null,
      },

      createdBy: {
        type: Schema.Types.ObjectId,
        ref: "User",
        default: null,
      },

      updatedBy: {
        type: Schema.Types.ObjectId,
        ref: "User",
        default: null,
      },
    },
    { timestamps: true }
  );

  TranscriptSchema.index(
    {
      student: 1,
      academicYearFrom: 1,
      academicYearTo: 1,
      termFrom: 1,
      termTo: 1,
      kind: 1,
    },
    { unique: false }
  );

  return connection.model("Transcript", TranscriptSchema);
};