const test=require('node:test');const assert=require('node:assert/strict');
const cal=require('../src/services/tenant/academicCalendarService');
const disc=require('../src/services/tenant/disciplineService');
const docs=require('../src/services/tenant/studentDocumentService');

test('calendar date keys are date-only and ranges cannot reverse',()=>{assert.equal(cal.normalizeDateKey('2026-09-03'),'2026-09-03');assert.equal(cal.assertDateRange('2026-09-03','2026-09-05').end,'2026-09-05');assert.throws(()=>cal.assertDateRange('2026-09-05','2026-09-03'),/before/);assert.throws(()=>cal.normalizeDateKey('2026-02-30'),/invalid/);});
test('calendar terms normalize school vocabulary',()=>{assert.equal(cal.normalizeTerm('Semester 1'),'Term 1');assert.equal(cal.normalizeTerm('2'),'Term 2');assert.equal(cal.normalizeTerm('Term 3'),'Term 3');});
test('calendar portal visibility is published-only and scoped',()=>{const f=cal.calendarVisibilityFilterForStudent({classId:'c1',sectionId:'s1',streamId:'r1',academicYear:'2026/2027',term:2});assert.equal(f.$and[0].status,'active');assert.ok(JSON.stringify(f).includes('migrationQuarantinedAt'));assert.ok(JSON.stringify(f).includes('Term 2'));});
test('student with no section/stream cannot inherit scoped calendar events',()=>{const f=cal.calendarVisibilityFilterForStudent({classId:'c1',academicYear:'2026/2027',term:1});const text=JSON.stringify(f);assert.doesNotMatch(text,/"sectionId":"s/);assert.ok(text.includes('"sectionId":null'));assert.ok(text.includes('"streamId":null'));});
test('archived calendar events cannot be reactivated',()=>{assert.throws(()=>cal.assertCalendarLifecycle({status:'archived'},'active'),/immutable/);});
test('calendar hard delete is limited to never-published draft',()=>{assert.equal(cal.assertCalendarDeleteAllowed({status:'draft'}),true);assert.throws(()=>cal.assertCalendarDeleteAllowed({status:'active'}),/never-published/);assert.throws(()=>cal.assertCalendarDeleteAllowed({status:'draft',firstPublishedAt:new Date()}),/never-published/);});
test('calendar build values records publication and revision',()=>{const v=cal.buildCalendarValues({input:{title:'Term opens',type:'Term',startDate:'2026-09-01',status:'active',term:'1'},scope:{classGroup:null},actorId:'u'});assert.equal(v.startDateKey,'2026-09-01');assert.equal(v.term,'Term 1');assert.ok(v.firstPublishedAt);assert.equal(v.revision,0);const u=cal.buildCalendarValues({input:{title:'Term opens',type:'Term',startDate:'2026-09-01',status:'active'},scope:{},current:{status:'active',revision:2}});assert.equal(u.revision,3);});
test('calendar CSV neutralizes spreadsheet formulas and regex is escaped',()=>{assert.match(cal.csvCell('=cmd'),/^"'/);assert.equal(cal.escapeRegExp('a.*b'),'a\\.\\*b');});

test('discipline case numbers use dated random shape rather than last+1',()=>{assert.match(disc.newCaseNumber(new Date('2026-08-29T00:00:00Z')),/^DC-20260829-[A-F0-9]{8}$/);});
test('closed discipline cases require explicit reopen',()=>{assert.throws(()=>disc.assertTransition({status:'resolved'},'investigating'),/reopened/);assert.equal(disc.assertTransition({status:'resolved'},'investigating',{reopen:true}),'investigating');});
test('discipline create snapshots student academic identity',()=>{const v=disc.buildCaseValues({student:{_id:'s',regNo:'R1',fullName:'Ada',classId:'c',className:'P5',academicYear:'2026',term:2,status:'active'},input:{incidentDate:'2026-08-20',category:'Conduct',description:'Incident',status:'open'}});assert.equal(v.studentRegNo,'R1');assert.equal(v.className,'P5');assert.equal(v.term,2);});
test('discipline delete fails after visibility action evidence or closure',()=>{assert.equal(disc.assertDeleteAllowed({status:'open',actions:[],attachments:[]}),true);assert.throws(()=>disc.assertDeleteAllowed({status:'open',studentVisible:true}),/Only unpublished/);assert.throws(()=>disc.assertDeleteAllowed({status:'resolved'}),/Only unpublished/);});
test('discipline evidence accepts only PDF and safe images',()=>{assert.equal(disc.safeEvidenceFile({buffer:Buffer.from('x'),size:1,mimetype:'application/pdf'}),true);assert.throws(()=>disc.safeEvidenceFile({buffer:Buffer.from('x'),size:1,mimetype:'text/html'}),/Only PDF/);});
test('discipline visibility filters are student-owned and explicit',()=>{assert.deepEqual(disc.disciplineVisibilityFilterForStudent('s1'),{student:'s1',isDeleted:{$ne:true},migrationQuarantinedAt:null,studentVisible:true});assert.equal(disc.disciplineVisibilityFilterForStudent('s1',{parent:true}).parentVisible,true);});

test('student document status and expiry are conservative',()=>{assert.equal(docs.normalizeDocumentStatus('verified'),'verified');assert.throws(()=>docs.normalizeDocumentStatus('approved'),/Invalid/);assert.equal(docs.effectiveDocumentStatus({status:'verified',expiryDate:new Date('2020-01-01')},new Date('2026-01-01')),'expired');});
test('student document files reject active HTML/script content types',()=>{assert.equal(docs.safeDocumentFile({buffer:Buffer.from('x'),size:1,mimetype:'image/png'}),true);assert.throws(()=>docs.safeDocumentFile({buffer:Buffer.from('<script>'),size:8,mimetype:'text/html'}),/Only PDF/);});
test('student document stored URLs only allow HTTP(S)',()=>{assert.match(docs.safeStoredUrl('https://example.com/a.pdf'),/^https:/);assert.equal(docs.safeStoredUrl('javascript:alert(1)'),'');assert.equal(docs.safeStoredUrl('data:text/html,x'),'');});
test('document replacement resets verification and increments revision',()=>{const v=docs.buildDocumentLifecycleValues({current:{_id:'d',status:'verified',revision:4,studentVisible:true,parentVisible:true},input:{},fileReplaced:true});assert.equal(v.status,'pending');assert.equal(v.revision,5);assert.equal(v.verifiedAt,null);});
test('document rejection requires reason and date ranges are valid',()=>{assert.throws(()=>docs.buildDocumentLifecycleValues({current:{_id:'d',status:'pending'},input:{status:'rejected'}}),/reason/);assert.throws(()=>docs.buildDocumentLifecycleValues({current:{_id:'d'},input:{issueDate:'2026-09-10',expiryDate:'2026-09-01'}}),/before/);});
test('student document portal filters never use legacy studentId',()=>{assert.deepEqual(docs.studentDocumentFilter('s',{parent:true}),{student:'s',isDeleted:{$ne:true},migrationQuarantinedAt:null,parentVisible:true});});
