const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');

test('admin mounts fail closed on full Calendar Discipline and Student Documents dependencies',()=>{const s=read('src/routes/tenant/admin/index.js');assert.match(s,/\/academic-calendar"[\s\S]*requireTenantModels\(\["AcademicEvent", "Class", "Section", "Stream", "Student", "Notification"\], \{ match: "all" \}\)/);assert.match(s,/\/discipline"[\s\S]*requireTenantModels\(\["DisciplineCase", "Student", "Notification"\], \{ match: "all" \}\)/);assert.match(s,/\/student-docs"[\s\S]*requireTenantModels\(\["StudentDoc", "Student", "Applicant", "Notification"\], \{ match: "all" \}\)/);});

test('student parent and staff portal mounts fail closed on canonical models',()=>{const st=read('src/routes/tenant/students/index.js'),pa=read('src/routes/tenant/parents/index.js'),sf=read('src/routes/tenant/staff/index.js');assert.match(st,/\["AcademicEvent", "Student"\]/);assert.match(st,/\["DisciplineCase", "Student"\]/);assert.match(st,/\["StudentDoc", "Student"\]/);assert.match(pa,/\["Parent", "Student", "AcademicEvent"\]/);assert.match(pa,/\["Parent", "Student", "DisciplineCase"\]/);assert.match(pa,/\["Parent", "Student", "StudentDoc"\]/);assert.match(sf,/\["Staff", "AcademicEvent"\]/);});

test('calendar portal readers use published canonical visibility instead of legacy fields',()=>{for(const f of ['src/controllers/tenant/students/calendarController.js','src/controllers/tenant/parents/calendarController.js']){const s=read(f);assert.match(s,/calendarVisibilityFilterForStudent/);assert.doesNotMatch(s,/studentId\s*:|programId\s*:|classId\s*:\s*student\._id/);}assert.match(read('src/controllers/tenant/staff/calendarController.js'),/publicCalendarFilter/);});

test('calendar admin writes use revision guards and never blindly bulk update',()=>{const s=read('src/controllers/tenant/admin/academicCalendarController.js');assert.match(s,/revision:Number\(expected\)/);assert.match(s,/This calendar event changed in another session/);const bulk=s.slice(s.indexOf('bulkArchive:'),s.indexOf('importCsv:'));assert.doesNotMatch(bulk,/updateMany|deleteMany/);assert.match(bulk,/replaceOne/);});

test('calendar CSV is whole-batch preflighted and formula-safe exported',()=>{const s=read('src/controllers/tenant/admin/academicCalendarController.js');assert.match(s,/Import rejected before writing/);assert.match(s,/insertMany\(docs,\{ordered:true\}\)/);assert.match(s,/map\(csvCell\)/);assert.doesNotMatch(s,/new RegExp\(q,/);});

test('calendar browser renderer has no data-backed innerHTML and RCDATA is escaped',()=>{assert.doesNotMatch(read('public/js/academic-calendar.js'),/innerHTML\s*=|insertAdjacentHTML/);const s=read('views/tenant/academic-calendar/index.ejs');assert.match(s,/replace\(\/<\/g,"\\\\u003c"\)/);assert.match(s,/canDelete:/);});

test('discipline case identity is random and closed cases need explicit reopen',()=>{const service=read('src/services/tenant/disciplineService.js');assert.match(service,/crypto\.randomBytes\(4\)/);assert.match(service,/Closed discipline cases must be explicitly reopened before further changes/);const c=read('src/controllers/tenant/admin/disciplineController.js');assert.doesNotMatch(c,/last\s*\+\s*1|sort\([^)]*caseNo[^)]*-1/);assert.match(c,/createCaseWithRetry/);});

test('discipline mutations use compare-and-set revisions including evidence and actions',()=>{const s=read('src/controllers/tenant/admin/disciplineController.js');assert.match(s,/function guardedSet/);assert.match(s,/revision: expected/);assert.match(s,/\$inc: \{ revision: 1 \}/);assert.match(s,/safeDestroy\(uploaded\.public_id/);assert.match(s,/status: \{ \$nin: \["resolved", "dismissed"\] \}/);});

test('discipline action visibility is private by default and explicit in all layers',()=>{const model=read('src/models/tenant/DisciplineCase.js'),svc=read('src/services/tenant/disciplineService.js'),admin=read('src/controllers/tenant/admin/disciplineController.js'),mig=read('scripts/lib/migrateDiscipline.js');assert.match(model,/visibleToStudent:\{type:Boolean,default:false\},visibleToParent:\{type:Boolean,default:false\}/);assert.match(svc,/a\?\.\[visibilityKey\]===true/);assert.match(admin,/visibleToStudent: a\.visibleToStudent === true, visibleToParent: a\.visibleToParent === true/);assert.match(mig,/visibleToStudent: a\?\.visibleToStudent === true, visibleToParent: a\?\.visibleToParent === true/);});

test('student and parent discipline readers require explicit visibility and parent-specific action redaction',()=>{const st=read('src/controllers/tenant/students/disciplineController.js'),pa=read('src/controllers/tenant/parents/disciplineController.js');assert.match(st,/disciplineVisibilityFilterForStudent\(student\._id\)/);assert.match(pa,/disciplineVisibilityFilterForStudent\(student\._id,\{parent:true\}\)/);assert.match(pa,/safeCaseSummary\(row,\{parent:true\}\)/);});

test('discipline evidence never exposes raw cloud URLs in page JSON',()=>{const c=read('src/controllers/tenant/admin/disciplineController.js'),v=read('views/tenant/discipline/index.ejs');const meta=c.slice(c.indexOf('const meta ='),c.indexOf('const totalPages'));assert.doesNotMatch(meta,/secure_url|publicId|\.url\s*\|\|\s*c\./);assert.match(meta,/\/admin\/discipline\/\$\{c\._id\}\/file/);assert.doesNotMatch(v,/secure_url|publicId/);assert.match(v,/replace\(\/<\/g,"\\\\u003c"\)/);});

test('discipline browser renderer is DOM-safe',()=>{assert.doesNotMatch(read('public/js/discipline.js'),/innerHTML\s*=|insertAdjacentHTML/);});

test('student documents use verification expiry and protected same-origin downloads',()=>{const c=read('src/controllers/tenant/admin/studentDocsController.js'),s=read('src/services/tenant/studentDocumentService.js');assert.match(s,/pending|verified|rejected|expired/);assert.match(s,/safeStoredUrl/);assert.match(c,/downloadUrl:`\/admin\/student-docs\/\$\{r\._id\}\/file`/);assert.match(c,/revision:expected|revision: expected/);});

test('student document replacement and soft removal are compare-and-set guarded',()=>{const s=read('src/controllers/tenant/admin/studentDocsController.js');assert.match(s,/StudentDoc\.updateOne\([\s\S]*revision:expected/);assert.match(s,/This document changed in another session/);assert.match(s,/safeDestroy/);});

test('student and parent document file endpoints enforce ownership filters',()=>{const st=read('src/controllers/tenant/students/documentsController.js'),pa=read('src/controllers/tenant/parents/documentsController.js');assert.match(st,/findOne\(\{_id:req\.params\.id,\.\.\.studentDocumentFilter\(student\._id\)\}\)/);assert.match(pa,/canAccessChild\(ctx\.parent,ctx\.student\._id\)/);assert.match(pa,/studentDocumentFilter\(ctx\.student\._id,\{parent:true\}\)/);for(const v of ['views/students/documents.ejs','views/parents/documents.ejs'])assert.doesNotMatch(read(v),/doc\.url|publicId|secure_url/);});

test('Applicant to Student document bridge is Pending and private by default',()=>{const s=read('src/utils/studentDocs.js');assert.match(s,/status: "pending"/);assert.match(s,/studentVisible: false/);assert.match(s,/parentVisible: false/);});

test('student document admin bootstrap contains only same-origin file URL and safe RCDATA',()=>{const s=read('views/tenant/student-docs/index.ejs');assert.match(s,/url: d\.downloadUrl \|\| \(d\._id \? "\/admin\/student-docs\/"/);assert.doesNotMatch(s,/url:\s*d\.doc\?\.url|publicId:/);assert.match(s,/replace\(\/<\/g,"\\\\u003c"\)/);assert.doesNotMatch(read('public/js/student-docs.js'),/innerHTML\s*=|insertAdjacentHTML/);});

test('new parent portal forms are CSP-safe without inline event handlers',()=>{for(const f of ['views/parents/calendar.ejs','views/parents/discipline.ejs','views/parents/documents.ejs']){const s=read(f);assert.doesNotMatch(s,/\son(?:click|change|submit|load|error|input|focus|blur)=/i);assert.match(s,/>View<|>View\s*</);}});

test('staff calendar reuses an existing approved portal stylesheet',()=>{const s=read('views/staff/calendar.ejs');assert.match(s,/\/css\/student-portal\.css/);assert.doesNotMatch(s,/staff-portal\.css/);});

test('new portal views contain no inline executable scripts',()=>{for(const f of ['views/students/calendar.ejs','views/students/discipline.ejs','views/students/documents.ejs','views/parents/calendar.ejs','views/parents/discipline.ejs','views/parents/documents.ejs','views/staff/calendar.ejs']){const s=read(f);assert.doesNotMatch(s,/<script(?![^>]*src=)[^>]*>[\s\S]*?<\/script>/i,f);}});

test('all three migrations are wired before tenant index synchronization',()=>{const pkg=JSON.parse(read('package.json'));assert.equal(pkg.scripts['migrate:academic-calendar'],'node scripts/migrate-academic-calendar.js');assert.equal(pkg.scripts['migrate:discipline'],'node scripts/migrate-discipline.js');assert.equal(pkg.scripts['migrate:student-docs'],'node scripts/migrate-student-docs.js');const s=read('scripts/create-indexes.js'),indexAt=s.indexOf('createModelIndexes(label, tenantModels)');for(const call of ['migrateAcademicCalendar(tenantModels)','migrateDiscipline(tenantModels)','migrateStudentDocs(tenantModels)']){assert.ok(s.indexOf(call)>=0);assert.ok(s.indexOf(call)<indexAt);}});

test('new school record EJS surfaces compile',()=>{const ejs=require('ejs');for(const f of ['views/tenant/academic-calendar/index.ejs','views/tenant/discipline/index.ejs','views/tenant/student-docs/index.ejs','views/students/calendar.ejs','views/students/discipline.ejs','views/students/documents.ejs','views/parents/calendar.ejs','views/parents/discipline.ejs','views/parents/documents.ejs','views/staff/calendar.ejs'])assert.doesNotThrow(()=>ejs.compile(read(f),{filename:path.join(root,f)}),f);});
