const test=require('node:test');const assert=require('node:assert/strict');
const {migrateAcademicCalendar}=require('../scripts/lib/migrateAcademicCalendar');
const {migrateDiscipline}=require('../scripts/lib/migrateDiscipline');
const {migrateStudentDocs}=require('../scripts/lib/migrateStudentDocs');
let seq=1;const id=()=>(seq++).toString(16).padStart(24,'0');
function collection(rows){return{rows,find(){return{toArray:async()=>rows.map(x=>({...x}))}},async updateOne(filter,update){const r=rows.find(x=>String(x._id)===String(filter._id));if(r)Object.assign(r,update.$set||{});return{modifiedCount:r?1:0}}};}
function model(rows){return{collection:collection(rows)};}

test('calendar migration resolves legacy name/code scope without broadening it',async()=>{const c=id(),sec=id(),stream=id();const row={_id:id(),title:'Sports Day',className:'Senior One',sectionCode:'A',streamName:'Blue',date:'2026-09-10',status:'published'};const AcademicEvent=model([row]);const Class=model([{_id:c,name:'Senior One',code:'S1',status:'active'}]);const Section=model([{_id:sec,name:'Alpha',code:'A',classId:c,status:'active'}]);const Stream=model([{_id:stream,name:'Blue',code:'BLU',classId:c,sectionId:sec,status:'active'}]);const out=await migrateAcademicCalendar({AcademicEvent,Class,Section,Stream});assert.equal(out.quarantined,0);assert.equal(String(row.classGroup),c);assert.equal(String(row.sectionId),sec);assert.equal(String(row.streamId),stream);assert.equal(row.status,'active');assert.equal(row.startDateKey,'2026-09-10');});

test('published calendar migration quarantines unresolved or inactive scope',async()=>{const c=id();const a={_id:id(),title:'A',className:'Missing',date:'2026-09-10',status:'published'},b={_id:id(),title:'B',classId:c,date:'2026-09-11',status:'active'};const AcademicEvent=model([a,b]),Class=model([{_id:c,name:'Old Class',status:'inactive'}]),Section=model([]),Stream=model([]);const out=await migrateAcademicCalendar({AcademicEvent,Class,Section,Stream});assert.equal(out.quarantined,2);assert.equal(a.status,'draft');assert.match(a.migrationQuarantineReason,/class scope could not be resolved/i);assert.equal(b.status,'draft');assert.match(b.migrationQuarantineReason,/class is not active/i);});

test('calendar invalid date ranges are quarantined and never remain published',async()=>{const row={_id:id(),title:'Bad',startDate:'bad-date',status:'active'};const out=await migrateAcademicCalendar({AcademicEvent:model([row]),Class:model([]),Section:model([]),Stream:model([])});assert.equal(out.quarantined,1);assert.equal(row.status,'draft');assert.ok(row.migrationQuarantinedAt);});

test('discipline migration replaces duplicate case numbers and keeps legacy actions private',async()=>{const student=id(),a={_id:id(),student,caseNo:'CASE-1',incidentDate:'2026-01-01',description:'A',actions:[{action:'Warning'}]},b={_id:id(),student,caseNo:'CASE-1',incidentDate:'2026-01-02',description:'B'};const DisciplineCase=model([a,b]),Student=model([{_id:student,regNo:'S1',fullName:'Student One',status:'active'}]);const out=await migrateDiscipline({DisciplineCase,Student});assert.equal(out.caseNumbersReplaced,1);assert.equal(a.actions[0].visibleToStudent,false);assert.equal(a.actions[0].visibleToParent,false);assert.notEqual(a.caseNo,b.caseNo);assert.equal(a.studentVisible,false);assert.equal(a.parentVisible,false);});

test('discipline migration quarantines unresolved students instead of publishing them',async()=>{const row={_id:id(),studentId:id(),incidentDate:'2026-01-01',description:'Legacy',studentVisible:true,parentVisible:true};const out=await migrateDiscipline({DisciplineCase:model([row]),Student:model([])});assert.equal(out.quarantined,1);assert.ok(row.migrationQuarantinedAt);assert.match(row.migrationQuarantineReason,/Student could not be resolved safely/);});

test('student document migration makes legacy visibility private by default',async()=>{const student=id(),row={_id:id(),student,url:'https://res.cloudinary.com/demo/raw/upload/file.pdf',publicId:'student/file',title:'Report'};const out=await migrateStudentDocs({StudentDoc:model([row]),Student:model([{_id:student,regNo:'S1',status:'active'}])});assert.equal(out.quarantined,0);assert.equal(out.privateByDefault,1);assert.equal(row.studentVisible,false);assert.equal(row.parentVisible,false);assert.equal(row.status,'pending');assert.equal(row.doc.publicId,'student/file');});

test('student document migration quarantines unsafe storage references',async()=>{const student=id(),row={_id:id(),student,url:'javascript:alert(1)',publicId:'x',title:'Bad'};const out=await migrateStudentDocs({StudentDoc:model([row]),Student:model([{_id:student,regNo:'S1',status:'active'}])});assert.equal(out.quarantined,1);assert.ok(row.migrationQuarantinedAt);assert.match(row.migrationQuarantineReason,/unsafe/);assert.equal(row.studentVisible,false);assert.equal(row.parentVisible,false);});
