const test=require('node:test');const assert=require('node:assert/strict');
const {migrateTransport}=require('../scripts/lib/migrateTransport');const {migrateAssets}=require('../scripts/lib/migrateAssets');const {migrateFacilities}=require('../scripts/lib/migrateFacilities');
let seq=1;const oid=()=>(seq++).toString(16).padStart(24,'0');
function same(a,b){return String(a)==String(b)}
function match(row,q){return Object.entries(q||{}).every(([k,v])=>{const actual=row[k];if(v&&typeof v==='object'&&!Array.isArray(v)){if('$in'in v)return v.$in.includes(actual);if('$ne'in v)return !same(actual,v.$ne);}return same(actual,v);});}
function coll(rows){return{rows,find(){return{toArray:async()=>rows.map(x=>({...x,assignments:Array.isArray(x.assignments)?x.assignments.map(y=>({...y})):x.assignments,maintenanceLogs:Array.isArray(x.maintenanceLogs)?x.maintenanceLogs.map(y=>({...y})):x.maintenanceLogs}))}},async findOne(q){return rows.find(r=>match(r,q))||null},async updateOne(q,u){const r=rows.find(x=>match(x,q));if(r)Object.assign(r,u.$set||{});return{modifiedCount:r?1:0}},async insertOne(doc){const d={_id:doc._id||oid(),...doc};rows.push(d);return{insertedId:d._id}},async countDocuments(q){return rows.filter(r=>match(r,q)).length}};}
const model=rows=>({collection:coll(rows)});

test('transport migration converts old learner count to reserved seats and protects capacity',async()=>{const r={_id:oid(),routeName:'North',code:'N1',assignedLearners:12,capacity:8,pickupPoints:['Gate'],status:'active'};const out=await migrateTransport({Transport:model([r]),TransportAssignment:model([]),Student:model([])});assert.equal(out.legacySeatsReserved,12);assert.equal(r.legacyAssignedLearners,12);assert.equal(r.assignedLearners,0);assert.equal(r.capacity,12);assert.equal(r.status,'active');});
test('transport migration quarantines active routes without pickup points',async()=>{const r={_id:oid(),routeName:'North',routeCode:'N1',capacity:10,status:'active'};const out=await migrateTransport({Transport:model([r]),TransportAssignment:model([]),Student:model([])});assert.equal(out.routesQuarantined,1);assert.equal(r.status,'inactive');assert.match(r.migrationQuarantineReason,/no pickup points/);});
test('transport migration keeps only one active assignment per student',async()=>{const student={_id:oid(),status:'active'},route={_id:oid(),routeName:'R',routeCode:'R',capacity:10,pickupPoints:['A']};const old={_id:oid(),student:student._id,route:route._id,status:'active',pickupPoint:'A',updatedAt:new Date('2026-01-01')},newer={_id:oid(),student:student._id,route:route._id,status:'active',pickupPoint:'A',updatedAt:new Date('2026-02-01')};const out=await migrateTransport({Transport:model([route]),TransportAssignment:model([old,newer]),Student:model([student])});assert.equal(out.assignmentsQuarantined,1);assert.equal(newer.status,'active');assert.equal(old.status,'ended');assert.match(old.migrationQuarantineReason,/Duplicate active assignment/);});
test('asset migration converts embedded maintenance and recomputes issued quantity',async()=>{const a={_id:oid(),assetId:'AST1',name:'Laptop',quantity:1,assignments:[{assignedTo:'Student',status:'Assigned',quantity:2}],maintenanceLogs:[{_id:oid(),issue:'Screen',status:'Open'}]};const maint=[];const out=await migrateAssets({Asset:model([a]),AssetMaintenance:model(maint)});assert.equal(out.maintenanceMigrated,1);assert.equal(a.quantity,2);assert.equal(a.assignedCount,2);assert.equal(a.status,'Maintenance');assert.equal(maint.length,1);assert.equal(maint[0].asset,a._id);assert.deepEqual(a.maintenanceLogs,[]);});
test('asset migration repairs duplicate tags without deleting history',async()=>{const a={_id:oid(),assetTag:'TAG',name:'A'},b={_id:oid(),assetTag:'TAG',name:'B'};await migrateAssets({Asset:model([a,b]),AssetMaintenance:model([])});assert.equal(a.assetTag,'TAG');assert.match(b.assetTag,/^TAG-/);});
test('facility migration quarantines globally duplicate room identities even across campuses',async()=>{const a={_id:oid(),name:'Lab 1',code:'L1',campus:'A',capacity:10},b={_id:oid(),name:'Lab 1',code:'L2',campus:'B',capacity:10};const out=await migrateFacilities({Classroom:model([a,b])});assert.equal(out.quarantined,1);assert.equal(a.status,'available');assert.equal(b.status,'inactive');assert.match(b.migrationQuarantineReason,/Duplicate room identity/);});
test('facility migration gives maintenance legacy rooms a reason',async()=>{const r={_id:oid(),name:'Hall',code:'H1',status:'maintenance',capacity:0};await migrateFacilities({Classroom:model([r])});assert.equal(r.capacity,1);assert.equal(r.maintenanceReason,'Legacy maintenance state');});
test('transport migration quarantines active assignments with pickup points outside the route',async()=>{const student={_id:oid(),status:'active'},route={_id:oid(),routeName:'R',routeCode:'R',capacity:10,pickupPoints:['Gate A'],status:'active'},a={_id:oid(),student:student._id,route:route._id,status:'active',pickupPoint:'Gate B'};const out=await migrateTransport({Transport:model([route]),TransportAssignment:model([a]),Student:model([student])});assert.equal(out.assignmentsQuarantined,1);assert.match(a.migrationQuarantineReason,/Pickup point is unresolved/);});
test('facility migration quarantines unavailable registered rooms already used by published timetable',async()=>{const r={_id:oid(),name:'Lab X',code:'LX',status:'maintenance',capacity:10},t={_id:oid(),roomKey:'lab x',status:'active',migrationQuarantinedAt:null};const out=await migrateFacilities({Classroom:model([r]),TimetableEntry:model([t])});assert.equal(out.quarantined,1);assert.match(r.migrationQuarantineReason,/Published timetable uses this unavailable classroom/);});
