const test=require('node:test');const assert=require('node:assert/strict');
const {migrateReporting}=require('../scripts/lib/migrateReporting');const {migrateAuditHealth}=require('../scripts/lib/migrateAuditHealth');const {migrateBackups}=require('../scripts/lib/migrateBackups');
let seq=1;const oid=()=>String(seq++).padStart(24,'0');
function same(a,b){return String(a)==String(b)}
function match(row,q){return Object.entries(q||{}).every(([k,v])=>{if(v&&typeof v==='object'&&!Array.isArray(v)){if('$ne'in v)return !same(row[k],v.$ne);if('$in'in v)return v.$in.some(x=>same(row[k],x));}return same(row[k],v);});}
function coll(rows){return{rows,find(){return{sort(){return this},toArray:async()=>rows.map(x=>({...x}))}},async updateOne(q,u){const r=rows.find(x=>match(x,q));if(r)Object.assign(r,u.$set||{});return{modifiedCount:r?1:0}}};}const model=rows=>({collection:coll(rows)});

test('report migration quarantines ready history without retrievable artifact',async()=>{const r={_id:oid(),status:'ready',reportType:'finance'};const out=await migrateReporting({ReportExport:model([r])});assert.equal(out.quarantined,1);assert.equal(r.status,'quarantined');assert.ok(r.migrationQuarantinedAt instanceof Date);assert.equal(r.accessType,'missing');});
test('report migration preserves authenticated artifact history and revision',async()=>{const r={_id:oid(),status:'ready',filePublicId:'p',revision:0};await migrateReporting({ReportExport:model([r])});assert.equal(r.accessType,'authenticated');assert.equal(r.revision,1);assert.match(r.fileName,/report-/);});
test('audit migration masks raw IP and creates pseudonymous hash',async()=>{const r={_id:oid(),ipAddress:'10.1.2.3'};await migrateAuditHealth({AuditLog:model([r])});assert.equal(r.ipAddress,'10.1.2.x');assert.match(r.ipHash,/^[a-f\d]{64}$/);assert.equal(r.reviewRevision,0);});
test('health migration quarantines duplicate active service identities',async()=>{const a={_id:oid(),serviceName:' Database ',region:' UG ',type:'Database',isDeleted:false,updatedAt:new Date('2026-02-01')},b={_id:oid(),serviceName:'database',region:'ug',type:'Database',isDeleted:false,updatedAt:new Date('2026-01-01')};const out=await migrateAuditHealth({SystemHealth:model([a,b])});assert.equal(out.quarantined,1);assert.equal(a.serviceKey,'database|ug');assert.ok(b.migrationQuarantinedAt instanceof Date);});
test('health migration quarantines missing service identity',async()=>{const r={_id:oid(),serviceName:'',region:'UG',type:'Storage'};const out=await migrateAuditHealth({SystemHealth:model([r])});assert.equal(out.quarantined,1);assert.match(r.migrationQuarantineReason,/Missing service identity/);});
test('backup migration rejects fake completed rows with no verifiable artifact',async()=>{const r={_id:oid(),status:'Completed',scope:'Full System'};const out=await migrateBackups({BackupJob:model([r])});assert.equal(out.quarantined,1);assert.equal(r.status,'Failed');assert.ok(r.failedAt instanceof Date);assert.match(r.failureReason,/integrity verified/);});
test('backup migration converts interrupted running jobs to failed',async()=>{const r={_id:oid(),status:'Running',filePublicId:'p',checksum:'x'};await migrateBackups({BackupJob:model([r])});assert.equal(r.status,'Failed');assert.match(r.failureReason,/Interrupted/);});
test('backup migration normalizes legacy media/database-only scopes and storage',async()=>{for(const scope of ['Media Only','Database Only']){const r={_id:oid(),status:'Scheduled',scope,storage:'Local'};await migrateBackups({BackupJob:model([r])});assert.equal(r.scope,'Full System');assert.equal(r.storage,'Cloudinary');assert.equal(r.revision,1);}});
