const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.join(__dirname,'..');
const read = p => fs.readFileSync(path.join(root,p),'utf8');

// Identity/session
test('platform auth guard no longer contains a platform user cache',()=>{const s=read('src/middleware/platform/guards.js');assert.doesNotMatch(s,/PLATFORM_USER_CACHE|USER_CACHE_TTL|cacheGet\(/);});
test('platform auth guard reloads active user on every protected request',()=>{const s=read('src/middleware/platform/guards.js');assert.match(s,/PlatformUser\.findOne/);assert.match(s,/isActive:\s*true/);assert.match(s,/isDeleted:\s*\{\s*\$ne:\s*true/);});
test('platform auth guard checks tokenVersion live',()=>assert.match(read('src/middleware/platform/guards.js'),/tokenVersion/));
test('platform auth guard enforces canonical idle timeout',()=>{const s=read('src/middleware/platform/guards.js');assert.match(s,/PlatformConfig/);assert.match(s,/sessionTimeoutMinutes/);assert.match(s,/platformLastActivityAt/);});
test('platform logout is POST CSRF protected',()=>{const s=read('src/routes/platform/auth.js');assert.match(s,/\["\/logout", "\/super-admin\/logout"\]/);assert.match(s,/platformOnly, csrfProtection, attachCsrfToken/);});
test('all authenticated platform and super-admin routes receive central CSRF',()=>assert.match(read('src/routes/platform/index.js'),/router\.use\(\["\/platform", "\/super-admin"\], platformOnly, csrfProtection, attachCsrfToken\)/));
test('platform navbar logout submits CSRF token',()=>{const s=read('views/platform/partials/navbar.ejs');assert.match(s,/action="\/logout"/);assert.match(s,/name="_csrf"/);});
test('super-admin login 2FA has separate pending session state',()=>{const s=read('src/controllers/platform/authController.js');assert.match(s,/platform2faPendingUserId/);assert.match(s,/platform2faHash/);assert.match(s,/platform2faExpiresAt/);assert.match(s,/platform2faTokenVersion/);});
test('super-admin email 2FA code has attempt and expiry bounds',()=>{const s=read('src/controllers/platform/authController.js');assert.match(s,/platform2faAttempts/);assert.match(s,/10 \* 60 \* 1000/);assert.match(s,/>= 5/);});
test('2FA routes are public-auth stage and CSRF limited',()=>{const s=read('src/routes/platform/auth.js');assert.match(s,/verify-login", csrfProtection, attachCsrfToken/);assert.match(s,/verify-login", authLimiter, csrfProtection, attachCsrfToken/);});
test('password reset consumes token atomically in one findOneAndUpdate',()=>{const s=read('src/controllers/platform/authController.js');const p=s.slice(s.indexOf('resetPassword: async'));assert.match(p,/findOneAndUpdate/);assert.match(p,/resetPasswordTokenHash/);assert.match(p,/resetPasswordExpires/);assert.match(p,/tokenVersion/);});
test('password reset production origin comes from configured site URL not raw Host',()=>{const s=read('src/controllers/platform/authController.js');assert.match(s,/PLATFORM_SITE_URL|PUBLIC_SITE_URL/);assert.doesNotMatch(s,/DEBUG_AUTH_TOKENS/);});
test('platform user status and role changes are revision guarded and revoke sessions',()=>{const s=read('src/controllers/platform/authController.js');assert.match(s,/positiveRevision\(req\.body\.revision\)/);assert.ok((s.match(/findOneAndUpdate\(\s*\n?\s*\{ _id: targetId, revision,/g)||[]).length>=2);assert.ok((s.match(/\$inc:\s*\{ revision:\s*1, tokenVersion:\s*1 \}/g)||[]).length>=2);});

// Settings/support/audit/reports
test('canonical platform settings use singleton config with revision',()=>{const s=read('src/models/platform/PlatformConfig.js');assert.match(s,/singletonKey/);assert.match(s,/uniq_platform_config_singleton/);assert.match(s,/revision/);});
test('platform security setting changes invalidate active superadmin sessions transactionally',()=>{const s=read('src/controllers/platform/settingsController.js');assert.match(s,/withTransaction/);assert.match(s,/PlatformUser\.updateMany/);assert.match(s,/tokenVersion:\s*1/);});
test('settings forms submit CSRF and revision',()=>{const s=read('views/platform/settings/index.ejs');assert.ok((s.match(/name="_csrf"/g)||[]).length>=3);assert.ok((s.match(/name="revision"/g)||[]).length>=3);});
test('support ticket model has revision and immutable status history evidence',()=>{const s=read('src/models/platform/SupportTicket.js');assert.match(s,/revision/);assert.match(s,/statusHistory/);assert.match(s,/fromStatus/);assert.match(s,/toStatus/);});
test('support assignment requires an active authorized platform support operator',()=>{const s=read('src/controllers/platform/supportTicketsController.js');assert.match(s,/isActive:\s*true/);assert.match(s,/support\.manage/);assert.match(s,/assignedTo/);});
test('support mutations compare browser revision and increment it',()=>{const s=read('src/controllers/platform/supportTicketsController.js');assert.match(s,/positiveRevision\(req\.body\.revision\)/);assert.match(s,/\{ _id: req\.params\.id, revision \}/);assert.match(s,/\{ _id: current\._id, revision, status: current\.status \}/);assert.match(s,/\$inc:\s*\{ revision:\s*1 \}/);});
test('support replies cannot append after terminal status',()=>{const s=read('src/controllers/platform/supportTicketsController.js');assert.match(s,/\["resolved", "closed"\]\.includes\(current\.status\)/);assert.match(s,/Reopen this ticket before replying/i);});
test('support forms carry CSRF and revision tokens',()=>{const s=read('views/platform/support-tickets/show.ejs');assert.ok((s.match(/name="_csrf"/g)||[]).length>=3);assert.ok((s.match(/name="revision"/g)||[]).length>=3);});
test('audit model sanitizes IP and metadata before validation',()=>{const s=read('src/models/platform/AuditLog.js');assert.match(s,/sanitizeAuditFields/);assert.match(s,/pre\("validate"/);assert.match(s,/ipHash/);});
test('audit model preserves existing pseudonymous IP hash on non-IP updates',()=>{const s=read('src/models/platform/AuditLog.js');assert.match(s,/isModified\("ipAddress"\)/);assert.match(s,/if \(sanitizeIp\)/);});
test('audit list and detail are private no-store surfaces',()=>{const s=read('src/controllers/platform/auditLogsController.js');assert.ok((s.match(/Cache-Control", "no-store"/g)||[]).length>=2);});
test('platform reports use canonical PlatformSubscription rather than Tenant status projection',()=>{const s=read('src/controllers/platform/reportsController.js');assert.match(s,/PlatformSubscription/);assert.match(s,/subscriptionEffectiveStatus|summarizeSubscriptions/);});
test('platform reports provide server CSV exports with formula safe shared service',()=>{const s=read('src/controllers/platform/reportsController.js');assert.match(s,/platformReportsService|csv\(/);const r=read('src/routes/platform/reports.js');assert.match(r,/tenants\.csv/);assert.match(r,/plans\.csv/);assert.match(r,/payments\.csv/);});

// Public directory
test('public quick search composes operational access filter with user filters',()=>{const s=read('src/controllers/platform/publicSearchController.js');assert.match(s,/addOperationalTenantCondition/);assert.match(s,/filter\.\$and = \[\.\.\.\(filter\.\$and \|\| \[\]\), \.\.\.andConditions\]/);});
test('public search never returns profile configured arbitrary apply URL',()=>{const s=read('src/controllers/platform/publicSearchController.js');assert.match(s,/applyUrl:\s*`\/schools\/\$\{encodeURIComponent\(item\.code\)\}\/apply`/);});
test('public directory landing and list use operational tenant condition',()=>{const s=read('src/controllers/platform/schoolsPublicController.js');assert.match(s,/addOperationalTenantCondition/);assert.match(s,/buildSchoolListBaseFilter/);});
test('featured school cache is shared in Redis and lifecycle invalidation makes suspension visible immediately',()=>{const c=read('src/controllers/platform/schoolsPublicController.js');const cache=read('src/services/platformPublicCacheService.js');assert.match(c,/getFeaturedSchoolsCache/);assert.match(c,/setFeaturedSchoolsCache/);assert.match(cache,/getRedisClient/);assert.match(cache,/setEx\(FEATURED_KEY/);assert.match(cache,/invalidatePublicSchoolCache/);});
test('public school profile lookup requires current trial or paid period',()=>{const s=read('src/controllers/platform/schoolsPublicController.js');const p=s.slice(s.indexOf('async function findTenantForPublicPage'),s.indexOf('function buildChipFilter'));assert.match(p,/addOperationalTenantCondition/);assert.match(p,/trialEndsAt/);assert.match(p,/subscriptionEndsAt/);});
test('public school resolver no longer caches tenant status for five minutes',()=>{const s=read('src/middleware/tenant/resolveTenantByCode.js');assert.doesNotMatch(s,/TENANT_CODE_CACHE|TENANT_CODE_TTL_MS|cacheGet|cacheSet/);});
test('public profile uses no-cache so lifecycle changes revalidate',()=>assert.match(read('src/controllers/platform/schoolsPublicController.js'),/Cache-Control", "no-cache, max-age=0"/));
test('public application handoff falls back to local apply path for external URL',()=>{const s=read('src/controllers/platform/schoolsPublicController.js');assert.match(s,/isHttpUrl\(configuredApply\)/);assert.match(s,/localApply \|\| "\/apply"/);});
test('public school page renders central application handoff link',()=>assert.match(read('src/controllers/platform/schoolsPublicController.js'),/`\/schools\/\$\{encodeURIComponent\(tenantDoc\.code \|\| ""\)\}\/apply`/));
test('public inquiry loads tenant models explicitly and fails if persistence unavailable',()=>{const s=read('src/controllers/platform/schoolsPublicController.js');const p=s.slice(s.indexOf('async inquiry'),s.indexOf('async review'));assert.match(p,/getTenantModels/);assert.match(p,/SchoolInquiry/);assert.match(p,/status\(503\)/);});
test('new public inquiry persists no raw user agent and uses keyed privacy hashes',()=>{const s=read('src/controllers/platform/schoolsPublicController.js');const p=s.slice(s.indexOf('async inquiry'),s.indexOf('async review'));assert.match(p,/privacyHmac\("inquiry-ip"/);assert.match(p,/userAgent:\s*""/);assert.match(p,/privacyHmac\("inquiry-user-agent"/);});
test('public review rechecks live operational school before tenant write',()=>{const s=read('src/controllers/platform/schoolsPublicController.js');const p=s.slice(s.indexOf('async review'));assert.match(p,/findTenantForPublicPage/);});

// Booking
test('public booking routes no longer expose google oauth setup or callback endpoints',()=>{const s=read('src/routes/platform/booking.js');assert.doesNotMatch(s,/google\/auth|oauth2\/callback/);});
test('booking controller never returns zoom host start_url',()=>assert.doesNotMatch(read('src/controllers/platform/bookingController.js'),/start_url/));
test('booking uses durable Google Calendar authorization plus zoom/google client configuration',()=>{const s=read('src/controllers/platform/bookingController.js');assert.doesNotMatch(s,/GOOGLE_OAUTH_REFRESH_TOKEN/);assert.match(s,/googleCalendar\.getCalendarClient\(\)/);assert.match(s,/GOOGLE_CALENDAR_RECONNECT_REQUIRED/);assert.match(s,/const bookingEnabled/);});
test('booking accepts only 30 45 or 60 minute public durations',()=>{const s=read('src/controllers/platform/bookingController.js');assert.match(s,/ALLOWED_DURATIONS = \[30, 45, 60\]/);assert.match(s,/refine\(\(n\) => ALLOWED_DURATIONS\.includes\(n\)\)/);});
test('booking validates offered business window lead time alignment and max advance',()=>{const s=read('src/controllers/platform/bookingController.js');assert.match(s,/function validBookingWindow/);assert.match(s,/MAX_ADVANCE_DAYS/);assert.match(s,/SLOT_INTERVAL_MIN/);assert.match(s,/LEAD_MINUTES/);});
test('booking model owns unique 15 minute slot segment claims',()=>{const s=read('src/models/platform/PlatformBooking.js');assert.match(s,/slotSegments/);assert.match(s,/uniq_platform_booking_slot_segment/);assert.match(s,/partialFilterExpression:\s*\{ blocksSlot: true \}/);});
test('booking controller claims durable slot before external freebusy and meeting creation',()=>{const s=read('src/controllers/platform/bookingController.js');const p=s.slice(s.indexOf('async function book'));const claim=p.indexOf('acquireSlotClaim');const busy=p.indexOf('freeBusyBetween');const zoom=p.indexOf('createZoomMeeting');assert.ok(claim>0&&busy>claim&&zoom>busy);});
test('booking availability combines Google busy and durable local bookings',()=>{const s=read('src/controllers/platform/bookingController.js');assert.match(s,/async function combinedBusy/);assert.match(s,/freeBusyBetween/);assert.match(s,/localBusyBetween/);});
test('expired unconfirmed booking claims are released before availability/claiming',()=>{const s=read('src/controllers/platform/bookingController.js');assert.match(s,/releaseExpiredClaims/);assert.match(s,/claimExpiresAt:\s*\{ \$lte: now \}/);assert.match(s,/blocksSlot:\s*false/);});
test('calendar failure compensates created zoom and releases claim',()=>{const s=read('src/controllers/platform/bookingController.js');const p=s.slice(s.indexOf('async function book'));assert.match(p,/deleteZoomMeeting/);assert.match(p,/failClaim/);});
test('lost final booking revision compensates both calendar and zoom resources',()=>{const s=read('src/controllers/platform/bookingController.js');assert.match(s,/Booking confirmation lost a revision race/);assert.match(s,/deleteCalendarEvent/);assert.match(s,/deleteZoomMeeting/);});
test('zoom external errors do not echo provider response bodies to visitor',()=>{const s=read('src/controllers/platform/bookingController.js');assert.doesNotMatch(s,/Zoom create meeting failed:.*response\.text|Zoom token error:.*response\.text/s);});
test('booking external HTTP calls have bounded timeouts',()=>{const s=read('src/controllers/platform/bookingController.js');assert.ok((s.match(/AbortSignal\.timeout\(10_000\)/g)||[]).length>=3);});
test('booking submit has stronger limiter than availability reads',()=>{const s=read('src/controllers/platform/bookingController.js');assert.match(s,/bookingSubmitLimiter/);assert.match(s,/15 \* 60 \* 1000/);const r=read('src/routes/platform/booking.js');assert.match(r,/bookingSubmitLimiter/);});
test('booking page CSP removes unsafe-inline script permission and nonces JSON-LD',()=>{const s=read('src/controllers/platform/bookingController.js');assert.doesNotMatch(s,/"script-src": \["'self'", "'unsafe-inline'"\]/);assert.match(s,/cspNonce/);assert.match(read('views/platform/public/schedule.ejs'),/application\/ld\+json" nonce="<%= cspNonce/);});

// Migration/index wiring
test('platform operations migration is wired after SaaS migration and before platform indexes',()=>{const s=read('scripts/create-indexes.js');const a=s.indexOf('migratePlatformSaas(platformModels)');const b=s.indexOf('migratePlatformOperations(platformModels)');const c=s.indexOf('createModelIndexes("platform", platformModels)');assert.ok(a>0&&b>a&&c>b);});
test('platform index loader includes config and booking authorities',()=>{const s=read('scripts/create-indexes.js');assert.match(s,/"PlatformConfig"/);assert.match(s,/"PlatformBooking"/);});
test('platform operations migration has explicit package command',()=>assert.equal(JSON.parse(read('package.json')).scripts['migrate:platform-operations'],'node scripts/migrate-platform-operations.js'));
test('platform operations migration imports legacy settings and scrubs audit data',()=>{const s=read('scripts/lib/migratePlatformOperations.js');assert.match(s,/PlatformSetting/);assert.match(s,/sanitizeAuditFields/);assert.match(s,/migrateSupportTickets/);assert.match(s,/migrateBookingClaims/);});
test('tenant inquiry migration scrubs legacy raw user agent and weak legacy IP hash',()=>{const s=read('scripts/lib/migrateInquiries.js');assert.match(s,/privacyHmac\("inquiry-user-agent"/);assert.match(s,/row\.userAgent = ""/);assert.match(s,/row\.ipHash = ""/);});
test('announcements mutations are covered by central CSRF and form token',()=>{assert.match(read('src/routes/platform/index.js'),/csrfProtection/);assert.match(read('views/platform/announcements/create.ejs'),/name="_csrf"/);assert.match(read('views/platform/announcements/show.ejs'),/name="_csrf"/);});
