const test = require('node:test');
const assert = require('node:assert/strict');
const mongoose = require('mongoose');
const migration = require('../scripts/lib/migratePlatformSaas');
const svc = require('../src/services/platformSubscriptionService');
const oid = () => new mongoose.Types.ObjectId();

function q(value){return{sort(){return this},limit(){return this},lean(){return Promise.resolve(value)}};}
function matches(row, filter={}) { return Object.entries(filter).every(([k,v])=>{ if(v&&typeof v==='object'&&!Array.isArray(v)){ if('$ne' in v) return String(row[k])!==String(v.$ne); } return String(row[k])===String(v); }); }
function memoryModel(seed=[]) {
  const rows=seed.map(x=>({...x}));
  return {
    rows,
    find(filter={}){ return q(rows.filter(r=>matches(r,filter)).map(r=>({...r}))); },
    findOne(filter={}){ return q(rows.find(r=>matches(r,filter)) ? {...rows.find(r=>matches(r,filter))} : null); },
    async updateOne(filter, update){ const r=rows.find(x=>matches(x,filter)); if(!r)return{modifiedCount:0}; Object.assign(r,update.$set||{}); if(update.$inc)for(const[k,v]of Object.entries(update.$inc))r[k]=Number(r[k]||0)+v; return{modifiedCount:1}; },
    async create(doc){ const x={_id:doc._id||oid(),...doc}; rows.push(x); return {...x,toObject(){return {...x}}}; },
  };
}
const basePlan=(x={})=>({_id:oid(),name:'Starter',code:'starter',billingModel:'school_only',pricePerSchool:50,pricePerStudent:0,platformSharePercent:0,currency:'USD',billingInterval:'monthly',trialDays:14,maxStudents:100,maxStaff:20,maxCampuses:1,enabledModules:[],featureFlags:{},revision:1,isDeleted:false,isActive:true,...x});

test('legacy trial past its end migrates fail closed as expired',()=>{ const now=new Date('2026-08-30'); const p=basePlan(); const t={_id:oid(),status:'trial',createdAt:new Date('2026-01-01'),trialEndsAt:new Date('2026-01-15')}; const s=migration.buildLegacySubscription({tenant:t,plan:p,now}); assert.equal(s.status,'expired'); assert.ok(s.expiredAt); });
test('legacy fixed active subscription derives a bounded paid end',()=>{ const now=new Date('2026-08-15'); const p=basePlan(); const t={_id:oid(),status:'active',subscriptionStartsAt:new Date('2026-08-01')}; const s=migration.buildLegacySubscription({tenant:t,plan:p,now}); assert.equal(s.currentPeriodEnd.toISOString(),'2026-09-01T00:00:00.000Z'); assert.equal(s.status,'active'); });
test('legacy active custom subscription without explicit end is quarantined and suspended',()=>{ const p=basePlan({billingInterval:'custom'}); const t={_id:oid(),status:'active',subscriptionStartsAt:new Date('2026-08-01')}; const s=migration.buildLegacySubscription({tenant:t,plan:p,now:new Date('2026-08-15')}); assert.equal(s.status,'suspended'); assert.equal(s.migrationQuarantined,true); assert.match(s.quarantineReason,/no explicit period end/i); });
test('legacy active fixed subscription whose derived period ended becomes past due',()=>{ const p=basePlan(); const t={_id:oid(),status:'active',subscriptionStartsAt:new Date('2026-01-01')}; const s=migration.buildLegacySubscription({tenant:t,plan:p,now:new Date('2026-08-30')}); assert.equal(s.status,'past_due'); });
test('plan normalization creates stable slug code and safe limits',()=>{ const p=migration.normalizePlanDocument({_id:oid(),name:' Gold Plan! ',billingModel:'oops',billingInterval:'oops',currency:'$',maxCampuses:0}); assert.equal(p.code,'gold-plan'); assert.equal(p.billingModel,'school_only'); assert.equal(p.billingInterval,'monthly'); assert.equal(p.currency,'USD'); assert.equal(p.maxCampuses,1); });
test('payment reference idempotency migration is tenant scoped', async()=>{ const tenantA=oid(),tenantB=oid(); const a={_id:oid(),tenantId:tenantA,provider:'bank',reference:'R1',type:'manual_adjust',status:'completed',amount:5,currency:'USD',migrationQuarantined:false,revision:1}; const b={_id:oid(),tenantId:tenantB,provider:'bank',reference:'R1',type:'manual_adjust',status:'completed',amount:5,currency:'USD',migrationQuarantined:false,revision:1}; const Payment=memoryModel([a,b]), Sub=memoryModel([]); const out=await migration.migratePayments({PlatformPayment:Payment,PlatformSubscription:Sub}); assert.equal(out.duplicateReferences,0); assert.notEqual(Payment.rows[0].referenceKey,Payment.rows[1].referenceKey); assert.equal(Payment.rows.every(r=>r.status==='completed'),true); });
test('same-tenant duplicate payment reference quarantines all but strongest winner', async()=>{ const tenant=oid(); const a={_id:oid(),tenantId:tenant,provider:'bank',reference:'R1',type:'manual_adjust',status:'completed',amount:5,currency:'USD',paidAt:new Date('2026-01-01'),migrationQuarantined:false,revision:1}; const b={_id:oid(),tenantId:tenant,provider:'bank',reference:'R1',type:'manual_adjust',status:'pending',amount:5,currency:'USD',createdAt:new Date('2026-01-02'),migrationQuarantined:false,revision:1}; const Payment=memoryModel([a,b]); const out=await migration.migratePayments({PlatformPayment:Payment,PlatformSubscription:memoryModel([])}); assert.equal(out.duplicateReferences,1); const quarantined=Payment.rows.filter(r=>r.migrationQuarantined); assert.equal(quarantined.length,1); assert.equal(quarantined[0].status,'reconciliation_required'); });
test('invalid legacy payment amount is quarantined', async()=>{ const row={_id:oid(),tenantId:oid(),provider:'manual',reference:'x',type:'manual_adjust',status:'completed',amount:0,currency:'USD',migrationQuarantined:false,revision:1}; const P=memoryModel([row]); await migration.migratePayments({PlatformPayment:P,PlatformSubscription:memoryModel([])}); assert.equal(P.rows[0].migrationQuarantined,true); assert.match(P.rows[0].quarantineReason,/amount/i); });
test('completed legacy payment without reference is quarantined', async()=>{ const row={_id:oid(),tenantId:oid(),provider:'manual',reference:'',type:'manual_adjust',status:'completed',amount:1,currency:'USD',migrationQuarantined:false,revision:1}; const P=memoryModel([row]); await migration.migratePayments({PlatformPayment:P,PlatformSubscription:memoryModel([])}); assert.equal(P.rows[0].status,'reconciliation_required'); assert.match(P.rows[0].quarantineReason,/no reference/i); });
test('subscription legacy payment links canonical current subscription and frozen plan', async()=>{ const tenant=oid(),planId=oid(),subId=oid(); const sub={_id:subId,tenantId:tenant,planId,revision:4,isDeleted:false,planSnapshot:{currency:'USD'}}; const row={_id:oid(),tenantId:tenant,provider:'bank',reference:'x',type:'school_subscription',status:'completed',amount:50,currency:'USD',migrationQuarantined:false,revision:1}; const P=memoryModel([row]); const out=await migration.migratePayments({PlatformPayment:P,PlatformSubscription:memoryModel([sub])}); assert.equal(out.subscriptionsLinked,1); assert.equal(String(P.rows[0].subscriptionId),String(subId)); assert.equal(String(P.rows[0].planId),String(planId)); assert.equal(P.rows[0].subscriptionRevision,4); });
test('legacy subscription payment currency mismatch is quarantined', async()=>{ const tenant=oid(); const sub={_id:oid(),tenantId:tenant,planId:oid(),revision:1,isDeleted:false,planSnapshot:{currency:'USD'}}; const row={_id:oid(),tenantId:tenant,provider:'bank',reference:'x',type:'school_subscription',status:'completed',amount:50,currency:'UGX',migrationQuarantined:false,revision:1}; const P=memoryModel([row]); await migration.migratePayments({PlatformPayment:P,PlatformSubscription:memoryModel([sub])}); assert.equal(P.rows[0].migrationQuarantined,true); assert.match(P.rows[0].quarantineReason,/currency/i); });
test('payment migration is idempotent for a valid normalized row', async()=>{ const tenant=oid(); const row={_id:oid(),tenantId:tenant,provider:'bank',reference:'x',referenceKey:svc.paymentReferenceKey('bank','x',tenant),type:'manual_adjust',status:'completed',amount:5,currency:'USD',migrationQuarantined:false,quarantineReason:'',revision:1}; const P=memoryModel([row]); const first=await migration.migratePayments({PlatformPayment:P,PlatformSubscription:memoryModel([])}); const snapshot=JSON.stringify(P.rows); const second=await migration.migratePayments({PlatformPayment:P,PlatformSubscription:memoryModel([])}); assert.equal(JSON.stringify(P.rows),snapshot); assert.equal(first.normalized,0); assert.equal(second.normalized,0); });
