const test=require('node:test');const assert=require('node:assert/strict');const {migrateReporting}=require('../scripts/lib/migrateReporting');
let seq=5000;const oid=()=>String(seq++).padStart(24,'0');function same(a,b){return String(a)===String(b)}
function model(rows){return{collection:{find(){return{toArray:async()=>rows.map(x=>({...x}))}},async updateOne(q,u){const r=rows.find(x=>same(x._id,q._id));if(r)Object.assign(r,u.$set||{});return{modifiedCount:r?1:0};}}};}
const checksum='a'.repeat(64);
test('migration scrubs legacy public file URL and quarantines ready row',async()=>{const r={_id:oid(),type:'invoices',status:'ready',fileUrl:'http://127.0.0.1/private.csv',checksum};const out=await migrateReporting({ReportExport:model([r])});assert.equal(r.fileUrl,'');assert.equal(r.accessType,'missing');assert.equal(r.status,'quarantined');assert.equal(out.scrubbedLegacyUrls,1);});
test('migration quarantines authenticated ready artifact missing checksum',async()=>{const r={_id:oid(),type:'payments',status:'ready',filePublicId:'p'};const out=await migrateReporting({ReportExport:model([r])});assert.equal(r.status,'quarantined');assert.equal(out.quarantined,1);assert.match(r.migrationQuarantineReason,/SHA-256/);});
test('migration keeps valid authenticated ready artifact ready',async()=>{const r={_id:oid(),type:'payments',status:'ready',filePublicId:'p',checksum};await migrateReporting({ReportExport:model([r])});assert.equal(r.status,'ready');assert.equal(r.accessType,'authenticated');assert.equal(r.migrationQuarantinedAt,null);});
test('migration recognizes analytics summary type',async()=>{const r={_id:oid(),type:'analytics_summary',status:'ready',filePublicId:'p',checksum};await migrateReporting({ReportExport:model([r])});assert.equal(r.status,'ready');});
test('migration quarantines unsupported report types',async()=>{const r={_id:oid(),type:'mystery',status:'ready',filePublicId:'p',checksum};await migrateReporting({ReportExport:model([r])});assert.equal(r.status,'quarantined');assert.match(r.migrationQuarantineReason,/unsupported/i);});
test('migration leaves valid failed history failed without requiring artifact',async()=>{const r={_id:oid(),type:'invoices',status:'failed'};await migrateReporting({ReportExport:model([r])});assert.equal(r.status,'failed');assert.equal(r.accessType,'missing');});
test('migration normalizes revision source and content type',async()=>{const r={_id:oid(),type:'finance_summary',status:'failed',revision:0,source:'weird',contentType:'text/html'};await migrateReporting({ReportExport:model([r])});assert.equal(r.revision,1);assert.equal(r.source,'export');assert.equal(r.contentType,'text/csv');});
test('migration normalizes negative rows and byte sizes',async()=>{const r={_id:oid(),type:'admissions',status:'failed',rowsCount:-7,byteSize:-4};await migrateReporting({ReportExport:model([r])});assert.equal(r.rowsCount,0);assert.equal(r.byteSize,0);});
test('migration creates a safe filename when legacy filename is absent',async()=>{const r={_id:oid(),type:'admissions',status:'failed',originalFileName:'../bad name.csv'};await migrateReporting({ReportExport:model([r])});assert.doesNotMatch(r.fileName,/\/|\\/);assert.match(r.fileName,/bad-name/);});
test('report migration is idempotent after normalization and quarantine',async()=>{const r={_id:oid(),type:'invoices',status:'ready',fileUrl:'https://legacy.invalid/x.csv',checksum};const M=model([r]);await migrateReporting({ReportExport:M});const first={...r};const out=await migrateReporting({ReportExport:M});assert.equal(r.status,first.status);assert.equal(r.fileUrl,'');assert.equal(out.scrubbedLegacyUrls,0);});
