const test = require('node:test');
const assert = require('node:assert/strict');
const {
  STUDENT_STATUSES,
  normalizeStudentStatus,
  csvCell,
  emergencyRegNo,
  allocateUniqueRegNo,
} = require('../src/services/tenant/studentLifecycleService');

test('student statuses are canonical and bounded', () => {
  assert.deepEqual(STUDENT_STATUSES, ['active','on_hold','suspended','graduated','archived']);
  assert.equal(normalizeStudentStatus(' SUSPENDED '), 'suspended');
  assert.equal(normalizeStudentStatus('deleted'), null);
});

test('student CSV cells neutralize spreadsheet formulas', () => {
  assert.equal(csvCell('=HYPERLINK("x")'), '"\'=HYPERLINK(""x"")"');
  assert.equal(csvCell('normal'), '"normal"');
});

test('emergency registration numbers are cryptographic-shaped and year scoped', () => {
  const a = emergencyRegNo(2026);
  const b = emergencyRegNo(2026);
  assert.match(a, /^REG\/2026\/[A-F0-9]{8}$/);
  assert.notEqual(a, b);
});

test('unique registration allocator retries collisions', async () => {
  let calls = 0;
  const Student = { exists: async ({ regNo }) => regNo === 'REG/2026/COLLIDE' };
  const value = await allocateUniqueRegNo(Student, async () => (++calls === 1 ? 'REG/2026/COLLIDE' : 'REG/2026/OK'));
  assert.equal(value, 'REG/2026/OK');
  assert.equal(calls, 2);
});

test('student creation retries an actual regNo duplicate-key race only for auto-generated numbers', async () => {
  const { createStudentWithRegRetry } = require('../src/services/tenant/studentLifecycleService');
  let creates = 0;
  const Student = {
    create: async (payload) => {
      creates += 1;
      if (creates === 1) {
        const err = new Error('E11000 duplicate key regNo');
        err.code = 11000;
        err.keyPattern = { regNo: 1 };
        throw err;
      }
      return payload;
    },
  };
  const created = await createStudentWithRegRetry(
    Student,
    { regNo: 'REG/2026/000001', firstName: 'A' },
    async () => 'REG/2026/000002',
    { autoGeneratedRegNo: true },
  );
  assert.equal(created.regNo, 'REG/2026/000002');
  assert.equal(creates, 2);
});

test('student creation does not rewrite an admin-supplied duplicate registration number', async () => {
  const { createStudentWithRegRetry } = require('../src/services/tenant/studentLifecycleService');
  const Student = {
    create: async () => {
      const err = new Error('E11000 duplicate key regNo');
      err.code = 11000;
      err.keyValue = { regNo: 'MANUAL-1' };
      throw err;
    },
  };
  await assert.rejects(
    () => createStudentWithRegRetry(Student, { regNo: 'MANUAL-1' }, async () => 'SHOULD-NOT-BE-USED', { autoGeneratedRegNo: false }),
    /duplicate key/,
  );
});
