const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const root=path.resolve(__dirname,'..');const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
test('all timetable portal mounts fail closed on canonical TimetableEntry dependencies',()=>{assert.match(read('src/routes/tenant/admin/index.js'),/\/timetable"[\s\S]*requireTenantModels\(\["TimetableEntry", "TimetableMutationLock", "Class", "Section", "Stream", "Subject", "Staff", "Student", "Notification"\]/);assert.match(read('src/routes/tenant/students/index.js'),/\["TimetableEntry", "Student", "Subject", "Staff", "Exam"\]/);assert.match(read('src/routes/tenant/parents/index.js'),/\["Student", "TimetableEntry", "Subject", "Staff"\]/);assert.match(read('src/routes/tenant/staff/index.js'),/\["Staff", "TimetableEntry", "Subject", "Class", "Section", "Stream"\]/);});
test('student timetable no longer reads shadow Timetable studentId classId programId contract',()=>{const s=read('src/controllers/tenant/students/timetableController.js');assert.doesNotMatch(s,/\{\s*Timetable\s*[,}]|studentId\s*:|programId\s*:/);assert.match(s,/studentTimetableFilter/);});
test('parent timetable uses canonical model and child authorization',()=>{const s=read('src/controllers/tenant/parents/timetableController.js');assert.match(s,/TimetableEntry/);assert.match(s,/canAccessChild/);assert.doesNotMatch(s,/ClassTimetable|\bSchedule\b|studentId\s*:/);});
test('staff timetable and dashboard use canonical teacher relation',()=>{assert.match(read('src/controllers/tenant/staff/timetableController.js'),/teacher:staff\._id/);assert.match(read('src/controllers/tenant/staff/dashboardController.js'),/teacher: staff\._id/);assert.doesNotMatch(read('src/controllers/tenant/staff/timetableController.js'),/staffId\s*:/);});
test('admin export is a server endpoint ordered before parameter routes',()=>{const s=read('src/routes/tenant/admin/timetable.js');assert.ok(s.indexOf('router.get("/export.csv"')>=0);assert.ok(s.indexOf('router.get("/export.csv"')<s.indexOf('router.post("/:id"'));assert.match(read('public/js/timetable.js'),/\/admin\/timetable\/export\.csv/);});
test('admin timetable uses optimistic revision guards and draft-only hard delete',()=>{const s=read('src/controllers/tenant/admin/timetableController.js');assert.match(s,/revision: expected/);assert.match(s,/Only never-published draft timetable entries can be permanently deleted/);assert.match(s,/publishedAt:null/);});
test('bulk lifecycle avoids blind updateMany and compensates partial writes',()=>{const s=read('src/controllers/tenant/admin/timetableController.js');const bulk=s.slice(s.indexOf('bulk: async'),s.indexOf('exportCsv: async'));assert.doesNotMatch(bulk,/TimetableEntry\.updateMany/);assert.doesNotMatch(bulk,/TimetableEntry\.deleteMany/);assert.match(bulk,/replaceOne|insertOne/);});
test('CSV import preflights intra-batch conflicts before writes',()=>{const s=read('src/controllers/tenant/admin/timetableController.js');assert.match(s,/Import rejected before writing/);assert.match(s,/conflictKindsBetween\(prepared\[i\],prepared\[j\]\)/);assert.match(s,/Rows \$\{j\+2\} and \$\{i\+2\} conflict/);});
test('admin timetable browser renderer has no database-backed innerHTML',()=>{assert.doesNotMatch(read('public/js/timetable.js'),/innerHTML\s*=/);});
test('student timetable uses static CSP-safe JS and no inline event handlers',()=>{const s=read('views/students/timetable.ejs');assert.match(s,/\/js\/student-timetable\.js/);assert.doesNotMatch(s,/<script>\s*\(function/);assert.doesNotMatch(s,/onclick=/);assert.doesNotMatch(read('public/js/student-timetable.js'),/innerHTML\s*=/);});
test('timetable JSON bootstraps are RCDATA escaped',()=>{const s=read('views/tenant/timetable/index.ejs');const blocks=[...s.matchAll(/<textarea[^>]+class="json-data"[\s\S]*?<%-([\s\S]*?)%><\/textarea>/g)];assert.ok(blocks.length>=5);for(const m of blocks)assert.match(m[1],/replace\(\/<\/g, "\\\\u003c"\)/);});
test('timetable migration is wired before tenant index synchronization',()=>{const pkg=JSON.parse(read('package.json'));assert.equal(pkg.scripts['migrate:timetable'],'node scripts/migrate-timetable.js');const s=read('scripts/create-indexes.js');assert.ok(s.indexOf('migrateTimetable(tenantModels)')>=0);assert.ok(s.indexOf('migrateTimetable(tenantModels)')<s.indexOf('createModelIndexes(label, tenantModels)'));});
test('timetable EJS surfaces compile',()=>{const ejs=require('ejs');for(const f of ['views/tenant/timetable/index.ejs','views/students/timetable.ejs','views/parents/timetable.ejs','views/staff/timetable.ejs'])assert.doesNotThrow(()=>ejs.compile(read(f),{filename:path.join(root,f)}),f);});

test('admin timetable closes bulk/status/notification concurrency gaps',()=>{const s=read('src/controllers/tenant/admin/timetableController.js');const bulk=s.slice(s.indexOf('bulk: async'),s.indexOf('exportCsv: async'));assert.match(bulk,/if\(action==="delete"\)\{/);assert.match(bulk,/else if\(!desired\)\{/);assert.match(bulk,/buildStatusValues\(row,desired/);assert.match(s,/withTimetableLocks/);assert.match(s,/if \(before\) await retireTimetableNotifications/);});
test('CSV import only resolves active academic hierarchy records',()=>{const s=read('src/controllers/tenant/admin/timetableController.js');assert.match(s,/Class\.find\(\{status:"active"\}\)/);assert.match(s,/Section\.find\(\{status:"active"\}\)/);assert.match(s,/Stream\.find\(\{status:"active"\}\)/);});
test('timetable mutation lock model is registered for tenant connections',()=>{const s=read('src/models/tenant/loadModels.js');assert.match(s,/TimetableMutationLock: defineModel\("TimetableMutationLock"\)/);assert.match(read('src/models/tenant/TimetableMutationLock.js'),/key: \{ type: String, required: true, unique: true/);});
