const test=require('node:test');const assert=require('node:assert/strict');const {migrateTimetable}=require('../scripts/lib/migrateTimetable');
let seq=1;const id=()=>(seq++).toString(16).padStart(24,'0');
function collection(rows){return{rows,find(){return{toArray:async()=>rows.map((x)=>({...x}))}},async updateOne(filter,update){const r=rows.find((x)=>String(x._id)===String(filter._id));if(r)Object.assign(r,update.$set||{});return{modifiedCount:r?1:0}}};}
function model(rows){return{collection:collection(rows)};}
function fixture(scopedSubject=false){const c=id(),sec=id(),stream=id(),sub=id(),teacher=id();const classes=[{_id:c,code:'S1-A',academicYear:'2026',term:1,status:'active'}],sections=[{_id:sec,code:'SEC-A',classId:c,status:'active'}],streams=[{_id:stream,code:'STR-A',classId:c,sectionId:sec,status:'active'}],subject={_id:sub,code:'MAT',title:'Math',status:'active',classId:c,academicYear:'2026',term:1};if(scopedSubject){subject.sectionId=String(sec);subject.streamId=String(stream);}const subjects=[subject],staff=[{_id:teacher,email:'teacher@example.com',status:'Active',isDeleted:false}];return{ids:{c,sec,stream,sub,teacher},models:{Class:model(classes),Section:model(sections),Stream:model(streams),Subject:model(subjects),Staff:model(staff)}};}
test('legacy timetable fields normalize to canonical references and schedule fields',async()=>{const f=fixture(true),row={_id:id(),classCode:'S1-A',sectionCode:'SEC-A',streamCode:'STR-A',courseCode:'MAT',staffId:f.ids.teacher,day:'Monday',start:'08:00',end:'09:00',venue:' Lab  1 ',status:'published',week:'odd'};const TimetableEntry=model([row]);await migrateTimetable({TimetableEntry,...f.models});assert.equal(String(row.classGroup),String(f.ids.c));assert.equal(String(row.subject),String(f.ids.sub));assert.equal(row.dayOfWeek,'Mon');assert.equal(row.startMinutes,480);assert.equal(row.status,'active');assert.equal(row.roomKey,'lab 1');assert.equal(row.weekPattern,'odd');assert.ok(row.publishedAt);});
test('subject-specific legacy rows are quarantined when section or stream scope is missing',async()=>{const f=fixture(true),row={_id:id(),classCode:'S1-A',courseCode:'MAT',day:'Monday',start:'08:00',end:'09:00',status:'active'};const TimetableEntry=model([row]);const out=await migrateTimetable({TimetableEntry,...f.models});assert.equal(out.quarantined,1);assert.equal(row.status,'inactive');assert.match(row.migrationQuarantineReason,/Subject\/(section|stream) scope conflicts/);});
test('unresolved active legacy rows are quarantined and downgraded',async()=>{const f=fixture(),row={_id:id(),classCode:'UNKNOWN',courseCode:'MAT',day:'Monday',start:'08:00',end:'09:00',status:'active'};const TimetableEntry=model([row]);const out=await migrateTimetable({TimetableEntry,...f.models});assert.equal(out.quarantined,1);assert.equal(row.status,'inactive');assert.ok(row.migrationQuarantinedAt);});
test('overlapping published conflicts quarantine the weaker row',async()=>{const f=fixture(),a={_id:id(),classCode:'S1-A',courseCode:'MAT',teacherEmail:'teacher@example.com',day:'Mon',startTime:'08:00',endTime:'09:00',status:'active',revision:5,updatedAt:new Date('2026-02-01')},b={_id:id(),classCode:'S1-A',courseCode:'MAT',teacherEmail:'teacher@example.com',day:'Mon',startTime:'08:30',endTime:'09:30',status:'active',revision:1,updatedAt:new Date('2026-01-01')};const TimetableEntry=model([a,b]);const out=await migrateTimetable({TimetableEntry,...f.models});assert.equal(out.conflictsQuarantined,1);assert.equal(a.status,'active');assert.equal(b.status,'inactive');assert.match(b.migrationQuarantineReason,/Published timetable conflict/);});
test('odd and even published legacy rows are retained together',async()=>{const f=fixture(),a={_id:id(),classCode:'S1-A',courseCode:'MAT',day:'Mon',startTime:'08:00',endTime:'09:00',status:'active',weekPattern:'odd'},b={_id:id(),classCode:'S1-A',courseCode:'MAT',day:'Mon',startTime:'08:00',endTime:'09:00',status:'active',weekPattern:'even'};const TimetableEntry=model([a,b]);const out=await migrateTimetable({TimetableEntry,...f.models});assert.equal(out.conflictsQuarantined,0);assert.equal(a.status,'active');assert.equal(b.status,'active');});
test('conflict quarantine is idempotently preserved on rerun',async()=>{const f=fixture(),a={_id:id(),classCode:'S1-A',courseCode:'MAT',day:'Mon',startTime:'08:00',endTime:'09:00',status:'active',revision:2},b={_id:id(),classCode:'S1-A',courseCode:'MAT',day:'Mon',startTime:'08:15',endTime:'09:15',status:'active',revision:1};const TimetableEntry=model([a,b]);await migrateTimetable({TimetableEntry,...f.models});const q=b.migrationQuarantinedAt;await migrateTimetable({TimetableEntry,...f.models});assert.equal(String(b.migrationQuarantinedAt),String(q));assert.match(b.migrationQuarantineReason,/Published timetable conflict/);});

test('legacy scoped references never broaden visibility when they cannot be resolved',async()=>{const f=fixture(),row={_id:id(),classCode:'S1-A',sectionCode:'MISSING',streamCode:'MISSING',courseCode:'MAT',teacherEmail:'missing@example.com',day:'Monday',start:'08:00',end:'09:00',status:'active'};const TimetableEntry=model([row]);const out=await migrateTimetable({TimetableEntry,...f.models});assert.equal(out.quarantined,1);assert.equal(row.status,'inactive');assert.match(row.migrationQuarantineReason,/Active section could not be resolved safely/);assert.match(row.migrationQuarantineReason,/Active stream could not be resolved safely/);assert.match(row.migrationQuarantineReason,/Teacher reference could not be resolved safely/);});
test('legacy active rows on inactive academic hierarchy are quarantined',async()=>{const f=fixture();f.models.Class.collection.rows[0].status='archived';const row={_id:id(),classCode:'S1-A',courseCode:'MAT',day:'Monday',start:'08:00',end:'09:00',status:'active'};const TimetableEntry=model([row]);const out=await migrateTimetable({TimetableEntry,...f.models});assert.equal(out.quarantined,1);assert.equal(row.status,'inactive');assert.match(row.migrationQuarantineReason,/Active class could not be resolved safely/);});
