const express=require("express");
const router=express.Router();
const ctrl=require("../../../controllers/tenant/admin/disciplineController");
const upload=require("../../../utils/uploadMemory");
router.get("/",ctrl.index);
router.get("/export.csv",ctrl.exportCsv);
router.get("/:id/file/:kind/:index",ctrl.file);
router.post("/",ctrl.create);
router.post("/:id/reopen",ctrl.reopen);
router.post("/:id/action",ctrl.addAction);
router.post("/:id/statement",upload.single("file"),ctrl.uploadStatement);
router.post("/:id/attachments",upload.array("files",5),ctrl.uploadAttachments);
router.post("/:id/delete",ctrl.softDelete);
router.post("/:id",ctrl.update);
module.exports=router;
