const express = require("express");
const router = express.Router();
const profileController = require("../../../controllers/tenant/admin/profileController");
const { logoUpload, faviconUpload, coverUpload, galleryUpload } = require("../../../middleware/uploads/schoolProfileMulter");
const { validateBufferedUploads } = require("../../../middleware/validateBufferedUploads");
const validateImages = validateBufferedUploads({ imageOnly: true, maxImagePixels: 25_000_000 });

router.get("/", profileController.page);
router.post("/", profileController.update);
router.post("/upload/logo", logoUpload, validateImages, profileController.uploadLogo);
router.post("/upload/favicon", faviconUpload, validateImages, profileController.uploadFavicon);
router.post("/upload/cover", coverUpload, validateImages, profileController.uploadCover);
router.post("/upload/gallery", galleryUpload, validateImages, profileController.uploadGallery);
router.delete("/gallery/:itemId", profileController.deleteGalleryItem);
router.post("/faqs", profileController.addFaq);
router.put("/faqs/:faqId", profileController.editFaq);
router.delete("/faqs/:faqId", profileController.deleteFaq);
router.post("/reviews/:reviewId/approve", profileController.approveReview);
router.post("/reviews/:reviewId/reject", profileController.rejectReview);
router.post("/reviews/:reviewId/feature", profileController.toggleFeaturedReview);
router.delete("/reviews/:reviewId", profileController.deleteReview);
router.post("/schools/:code/reviews", profileController.submitPublicReview);
module.exports = router;
