const express=require("express");
const router=express.Router();
const ctrl=require("../../../controllers/tenant/admin/studentDocsController");
const upload=require("../../../utils/uploadMemory");
const { validateBufferedUploads } = require("../../../middleware/validateBufferedUploads");
const validateDocs = validateBufferedUploads();
router.get("/",ctrl.index);
router.get("/export.csv",ctrl.exportCsv);
router.get("/:id/file",ctrl.file);
router.post("/",upload.single("file"), validateDocs,ctrl.create);
router.post("/:id/delete",ctrl.softDelete);
router.post("/:id",upload.single("file"), validateDocs,ctrl.update);
module.exports=router;
