const { getStudent, getStudentDisplayName, academicMeta, renderView } = require("./_helpers");
const { buildStudentContext, findVisibleAnnouncements, acknowledgeAnnouncement } = require("../../../services/tenant/announcementService");
const { loadPortalNotifications, markPortalNotificationRead, markAllPortalNotificationsRead, getPreference, savePreference, CATEGORY_FIELDS, portalNotificationFilter } = require("../../../services/tenant/notificationService");
// Explicitly retain the private-target visibility contract used internally by loadPortalNotifications.
void portalNotificationFilter;
const { markMessageOpenedFromNotification } = require("../../../services/tenant/messageService");
function preferenceInput(body={}){const out={inApp:body.inApp==="on"||body.inApp==="true"||body.inApp===true};CATEGORY_FIELDS.forEach(k=>{out[k]=k==="system"?true:(body[k]==="on"||body[k]==="true"||body[k]===true);});return out;}
module.exports={
  notifications:async(req,res)=>{try{if(!req.models)return res.status(500).send("Tenant models not loaded");const {Announcement}=req.models;const got=await getStudent(req),user=got?.user||null,student=got?.student||null;if(!user)return res.redirect("/login");const meta=academicMeta(student),context=await buildStudentContext(req,user,student);const [notifications,announcements,preference]=await Promise.all([loadPortalNotifications(req.models,user,["student"],{limit:100}).catch(()=>[]),Announcement?findVisibleAnnouncements(req,context,{limit:30,markRead:true}).catch(()=>[]):[],getPreference(req.models,user)]);const items=[...notifications.map(n=>({id:String(n._id),title:n.title||"Notification",message:n.message||n.body||"",category:n.category||n.type||"notification",read:!!n.effectiveRead,createdAt:n.createdAt||null,source:"notification",requiresAcknowledgement:false,url:n.url||""})),...announcements.map(a=>({id:String(a._id),title:a.title||"Announcement",message:a.body||"",category:a.category||"announcement",read:true,createdAt:a.publishedAt||a.createdAt||null,source:"announcement",requiresAcknowledgement:!!a.requiresAcknowledgement}))].sort((a,b)=>new Date(b.createdAt||0)-new Date(a.createdAt||0));return renderView(req,res,"students/notifications",{pageTitle:"Notifications",user,student,studentName:getStudentDisplayName(student,user),meta,notifications:items,preference,preferenceCategories:CATEGORY_FIELDS,stats:{total:items.length,unread:items.filter(i=>!i.read).length,announcements:items.filter(i=>i.source==="announcement").length}});}catch(err){console.error("Student notifications load error:",err);return res.status(500).send("Failed to load notifications");}},
  markNotificationRead:async(req,res)=>{try{const got=await getStudent(req),user=got?.user||null;if(!user)return res.redirect("/login");const notification=await markPortalNotificationRead(req.models,user,req.params.id,["student"]);if(notification)await markMessageOpenedFromNotification(req,notification,user).catch(()=>{});}catch{}return res.redirect("/student/notifications");},
  markAllRead:async(req,res)=>{try{const got=await getStudent(req),user=got?.user||null;if(user)await markAllPortalNotificationsRead(req.models,user,["student"]);}catch{}return res.redirect("/student/notifications");},
  savePreferences:async(req,res)=>{try{const got=await getStudent(req),user=got?.user||null;if(!user)return res.redirect("/login");await savePreference(req.models,user,preferenceInput(req.body));req.flash?.("success","Notification preferences updated.");}catch(err){req.flash?.("error",err.message||"Could not update preferences.");}return res.redirect("/student/notifications");},
  acknowledgeAnnouncement:async(req,res)=>{try{const got=await getStudent(req),user=got?.user||null,student=got?.student||null;if(!user)return res.redirect("/login");const context=await buildStudentContext(req,user,student),result=await acknowledgeAnnouncement(req,req.params.id,context);req.flash?.(result.ok?"success":"error",result.ok?"Announcement acknowledged.":"Announcement could not be acknowledged.");}catch{req.flash?.("error","Announcement could not be acknowledged.");}return res.redirect("/student/notifications");},
};
