const mongoose=require('mongoose');
const { escapeRegex, buildDateMatch }=require('../../../services/tenant/reportControlService');
const { redact, csvCell, parseIds }=require('../../../services/tenant/auditControlService');
const str=(v,max=180)=>String(v??'').trim().slice(0,max);
const actorObjectId=(req)=>{const raw=req.user?.userId||req.user?._id||req.session?.tenantUser?.id||null;return raw&&mongoose.Types.ObjectId.isValid(String(raw))?new mongoose.Types.ObjectId(String(raw)):null;};
function format(v){if(!v)return '-';const d=new Date(v);return Number.isNaN(d.getTime())?'-':d.toISOString().slice(0,16).replace('T',' ');}
function pretty(v){try{return JSON.stringify(redact(v??{}),null,2);}catch{return '{}';}}
function serialize(doc){return{id:String(doc._id),actor:doc.actorName||'System',actorEmail:doc.actorEmail||'',action:doc.action||'',module:doc.module||'',entityType:doc.entityType||'',entityId:doc.entityId?String(doc.entityId):'',entityLabel:doc.entityLabel||'',severity:doc.severity||'Info',ipAddress:doc.ipAddress||'',source:doc.source||'',createdAt:format(doc.createdAt),reviewed:!!doc.reviewed,reviewedAt:format(doc.reviewedAt),metadataPretty:pretty(doc.metadata),diffPretty:pretty({before:doc.before||null,after:doc.after||null})};}
function buildQuery(req){const q=str(req.query.q,80),action=str(req.query.action||'all'),moduleName=str(req.query.module||'all'),status=str(req.query.status||'all'),reviewed=str(req.query.reviewed||'all'),from=str(req.query.from||'',10),to=str(req.query.to||'',10);const mongo={};if(q){const rx=new RegExp(escapeRegex(q),'i');mongo.$or=['actorName','actorEmail','action','module','entityType','entityLabel','source'].map(k=>({[k]:rx}));}if(action!=='all')mongo.action=action;if(moduleName!=='all')mongo.module=moduleName;if(['Info','Warning','Critical'].includes(status))mongo.severity=status;if(reviewed==='yes')mongo.reviewed=true;if(reviewed==='no')mongo.reviewed={$ne:true};Object.assign(mongo,buildDateMatch(from,to,req.tenant?.timezone||'UTC','createdAt'));return{mongo,clean:{q,action,module:moduleName,status,reviewed,from,to}};}
async function stats(AuditLog,query,timezone){const now=new Date();const p=new Intl.DateTimeFormat('en-CA',{timeZone:timezone||'UTC',year:'numeric',month:'2-digit',day:'2-digit'}).format(now);const today=buildDateMatch(p,p,timezone,'createdAt');const [todayCount,critical,actors,modules]=await Promise.all([AuditLog.countDocuments({...query,...today}),AuditLog.countDocuments({...query,severity:'Critical'}),AuditLog.distinct('actorUserId',query),AuditLog.distinct('module',query)]);return{today:todayCount,critical,actors:actors.filter(Boolean).length,modules:modules.filter(Boolean).length};}
async function analytics(AuditLog,query){const rows=await AuditLog.aggregate([{$match:query},{$group:{_id:'$module',total:{$sum:1},critical:{$sum:{$cond:[{$eq:['$severity','Critical']},1,0]}},warnings:{$sum:{$cond:[{$eq:['$severity','Warning']},1,0]}},actors:{$addToSet:'$actorUserId'},latest:{$max:'$createdAt'}}},{$sort:{total:-1}},{$limit:100}]);return rows.map(r=>({module:r._id||'General',total:r.total,critical:r.critical,warnings:r.warnings,actors:(r.actors||[]).filter(Boolean).length,latest:format(r.latest)}));}
function toCsv(rows){const header=['When','Actor','Actor Email','Action','Module','Entity Type','Entity Label','Severity','Reviewed','IP Address','Source'];return [header.map(csvCell).join(','),...rows.map(r=>[r.createdAt,r.actor,r.actorEmail,r.action,r.module,r.entityType,r.entityLabel,r.severity,r.reviewed?'Yes':'No',r.ipAddress,r.source].map(csvCell).join(','))].join('\n');}
module.exports={
 index:async(req,res)=>{const{AuditLog}=req.models||{};if(!AuditLog)return res.status(503).send('Audit logs are unavailable.');const{mongo,clean}=buildQuery(req);const[docs,actions,modules,st,an]=await Promise.all([AuditLog.find(mongo).sort({createdAt:-1}).limit(500).lean(),AuditLog.distinct('action',{}),AuditLog.distinct('module',{}),stats(AuditLog,mongo,req.tenant?.timezone||'UTC'),analytics(AuditLog,mongo)]);return res.render('tenant/auditlogs/index',{tenant:req.tenant,csrfToken:req.csrfToken?.(),logs:docs.map(serialize),analytics:an,stats:st,filters:{actions:actions.filter(Boolean).sort(),modules:modules.filter(Boolean).sort()},query:clean});},
 exportCsv:async(req,res)=>{const{AuditLog}=req.models||{};if(!AuditLog)return res.status(503).send('Audit logs are unavailable.');const{mongo}=buildQuery(req);const ids=parseIds(req.query.ids,5000);if(ids.length)mongo._id={$in:ids.map(x=>new mongoose.Types.ObjectId(x))};const docs=await AuditLog.find(mongo).sort({createdAt:-1}).limit(10000).lean();const csv=toCsv(docs.map(serialize));res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition',`attachment; filename="audit-logs-${Date.now()}.csv"`);return res.send(csv);},
 markReviewed:async(req,res)=>{const{AuditLog}=req.models||{};if(!AuditLog)return res.status(503).json({ok:false,message:'Audit logs are unavailable.'});const ids=parseIds(req.body.ids,500);if(!ids.length)return res.status(400).json({ok:false,message:'Select at least one audit entry.'});const result=await AuditLog.updateMany({_id:{$in:ids.map(x=>new mongoose.Types.ObjectId(x))},reviewed:{$ne:true}},{$set:{reviewed:true,reviewedAt:new Date(),reviewedBy:actorObjectId(req)},$inc:{reviewRevision:1}});return res.json({ok:true,matched:result.matchedCount||0,modified:result.modifiedCount||0});}
};
