const mongoose=require('mongoose');
const backup=require('../../../services/tenant/backupService');
const { uploadBuffer, safeDestroy, authenticatedUrl }=require('../../../utils/cloudinaryUpload');
const { escapeRegex, csvCell }=require('../../../services/tenant/reportControlService');
const actorId=req=>req.user?.userId||req.user?._id||req.session?.tenantUser?.id||null;
const str=(v,max=300)=>String(v??'').trim().slice(0,max);
const oid=v=>mongoose.Types.ObjectId.isValid(String(v||''));
function fmt(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toISOString().slice(0,16).replace('T',' ');}
function serial(d){return{id:String(d._id),name:d.name||'',type:d.type||'Manual',scope:d.scope||'Full System',storage:d.storage||'Cloudinary',size:d.sizeLabel||'—',status:d.status||'Scheduled',createdAt:fmt(d.createdAt),scheduleAt:fmt(d.scheduleAt),completedAt:fmt(d.completedAt),retentionDays:Number(d.retentionDays||0),notes:d.notes||'',checksum:d.checksum||'',revision:Number(d.revision||1),downloadable:d.status==='Completed'&&d.accessType==='authenticated'&&!!d.filePublicId,restorable:d.status==='Completed'&&d.accessType==='authenticated'&&!!d.filePublicId&&!d.migrationQuarantinedAt};}
function restoreHistory(backups){const items=[];for(const d of backups)for(const r of d.restoreHistory||[])items.push({backupName:d.name||'',actor:r.actorName||'System',status:r.status||'Pending',scope:r.scope||d.scope||'Full System',note:r.note||'',createdAt:fmt(r.createdAt)});return items.sort((a,b)=>a.createdAt<b.createdAt?1:-1).slice(0,500);}
function actorName(req){return req.user?.fullName||req.user?.email||'Admin';}
async function createArtifact({models,tenant,job,actor,now=new Date()}){
 const key=backup.parseKey();
 const payload=await backup.snapshot(models,{scope:job.scope,tenant,now});
 const packed=await backup.packAsync(payload,key);
 const folderBase=process.env.CLOUDINARY_FOLDER||'classic-academy';const folder=`${folderBase}/${tenant?.code||tenant?._id||'tenant'}/backups`;
 const fileName=`backup-${str(tenant?.code||'tenant',50)}-${now.toISOString().replace(/[:.]/g,'-')}.cakb`;
 const upload=await uploadBuffer({buffer:packed.buffer,mimetype:'application/octet-stream',originalname:fileName,size:packed.buffer.length},folder,{resource_type:'raw',type:'authenticated',format:'cakb'});
 return{payload,packed,upload,fileName,actor};
}
async function executeJob(req,job){const{BackupJob}=req.models;const expected=Number(job.revision||1);const claim=await BackupJob.updateOne({_id:job._id,revision:expected,status:{$in:['Scheduled','Failed']},isDeleted:{$ne:true},migrationQuarantinedAt:null},{$set:{status:'Running',failureReason:'',failedAt:null,updatedBy:actorId(req)},$inc:{revision:1}});if(!(claim.modifiedCount||claim.nModified))throw new Error('Backup job changed in another session or is not runnable.');let art=null;try{art=await createArtifact({models:req.models,tenant:req.tenant,job,actor:actorId(req)});const finish=await BackupJob.updateOne({_id:job._id,revision:expected+1,status:'Running'},{$set:{status:'Completed',sizeBytes:art.packed.buffer.length,sizeLabel:backup.sizeLabel(art.packed.buffer.length),checksum:art.packed.checksum,plainHash:art.packed.plainHash,filePath:art.upload?.secure_url||'',filePublicId:art.upload?.public_id||'',fileResourceType:art.upload?.resource_type||'raw',accessType:'authenticated',artifactVersion:1,completedAt:new Date(),failedAt:null,failureReason:'',updatedBy:actorId(req)},$inc:{revision:1}});if(!(finish.modifiedCount||finish.nModified)){if(art.upload?.public_id)await safeDestroy(art.upload.public_id,art.upload.resource_type||'raw');throw new Error('Backup changed before artifact completion could be recorded.');}return true;}catch(err){if(art?.upload?.public_id){const current=await BackupJob.findOne({_id:job._id}).select('status filePublicId').lean().catch(()=>null);if(!current||current.status!=='Completed'||String(current.filePublicId||'')!==String(art.upload.public_id))await safeDestroy(art.upload.public_id,art.upload.resource_type||'raw');}await BackupJob.updateOne({_id:job._id,revision:expected+1,status:'Running'},{$set:{status:'Failed',failedAt:new Date(),failureReason:str(err.message,500),updatedBy:actorId(req)},$inc:{revision:1}}).catch(()=>{});throw err;}}
async function artifactBuffer(job){
 const maxBytes=150*1024*1024;
 if(job?.accessType!=='authenticated'||!job?.filePublicId)throw new Error('Legacy or unauthenticated backup artifacts are not downloadable or restorable; create a new backup.');
 const url=authenticatedUrl(job.filePublicId,job.fileResourceType||'raw');
 if(!url)throw new Error('Backup artifact is missing.');
 const response=await fetch(url,{redirect:'error',signal:AbortSignal.timeout(15000),headers:{Accept:'application/octet-stream'}});
 if(!response.ok)throw new Error(`Backup storage returned HTTP ${response.status}.`);
 const len=Number(response.headers.get('content-length')||0);
 if(len>maxBytes)throw new Error('Backup artifact exceeds restore safety limit.');
 if(!response.body?.getReader){const buf=Buffer.from(await response.arrayBuffer());if(buf.length>maxBytes)throw new Error('Backup artifact exceeds restore safety limit.');return buf;}
 const reader=response.body.getReader(),chunks=[];let total=0;
 try{for(;;){const{done,value}=await reader.read();if(done)break;const chunk=Buffer.from(value);total+=chunk.length;if(total>maxBytes){await reader.cancel().catch(()=>{});throw new Error('Backup artifact exceeds restore safety limit.');}chunks.push(chunk);}}
 finally{reader.releaseLock?.();}
 return Buffer.concat(chunks,total);
}
async function replaceFromPayload(models,payload,connection){await backup.validatePayloadForModels(payload,models);if(!connection?.startSession)throw new Error('Transactional restore is not supported by this tenant database connection.');const session=await connection.startSession();try{await session.withTransaction(async()=>{for(const row of payload.manifest){const M=models[row.model],docs=payload.collections[row.model]||[];await M.deleteMany({}, {session});if(docs.length)await M.insertMany(docs,{session,ordered:true});}});}finally{await session.endSession();}}
module.exports={
 index:async(req,res)=>{const{BackupJob}=req.models;const q=str(req.query.q,80),status=str(req.query.status||'all'),type=str(req.query.type||'all'),storage=str(req.query.storage||'all');const query={isDeleted:{$ne:true}};if(q){const rx=new RegExp(escapeRegex(q),'i');query.$or=[{name:rx},{notes:rx},{type:rx},{scope:rx},{status:rx}];}if(status!=='all')query.status=status;if(type!=='all')query.type=type;if(storage!=='all')query.storage=storage;const docs=await BackupJob.find(query).sort({createdAt:-1}).limit(300).lean();const successful=docs.filter(x=>x.status==='Completed').length,scheduled=docs.filter(x=>x.status==='Scheduled').length,failed=docs.filter(x=>x.status==='Failed').length,total=docs.reduce((a,b)=>a+Number(b.sizeBytes||0),0);const by=new Map();for(const d of docs){const k=d.storage||'Cloudinary',r=by.get(k)||{storage:k,count:0,totalBytes:0,completed:0,failed:0,latest:'—'};r.count++;r.totalBytes+=Number(d.sizeBytes||0);if(d.status==='Completed')r.completed++;if(d.status==='Failed')r.failed++;if(r.latest==='—')r.latest=fmt(d.createdAt);by.set(k,r);}return res.render('tenant/backup/index',{tenant:req.tenant,csrfToken:req.csrfToken?.(),backups:docs.map(serial),storageSummary:[...by.values()].map(r=>({...r,totalSize:backup.sizeLabel(r.totalBytes)})),restoreHistory:restoreHistory(docs),stats:{successful,scheduled,failed,storageUsed:backup.sizeLabel(total)},query:{q,status,type,storage}});},
 create:async(req,res)=>{try{const{BackupJob}=req.models;backup.parseKey();const name=str(req.body.name,220);if(!name)throw new Error('Backup name is required.');const scope=str(req.body.scope||'Full System');if(!['Full System','Config Only'].includes(scope))throw new Error('Unsupported backup scope.');const scheduleAt=req.body.scheduleAt?new Date(req.body.scheduleAt):null;if(scheduleAt&&Number.isNaN(scheduleAt.getTime()))throw new Error('Schedule time is invalid.');const retention=Math.max(1,Math.min(365,Number(req.body.retentionDays||30)||30));const job=await BackupJob.create({name,type:scheduleAt?'Scheduled':'Manual',scope,storage:'Cloudinary',retentionDays:retention,scheduleAt,status:'Scheduled',notes:str(req.body.notes,1000),createdBy:actorId(req),updatedBy:actorId(req),revision:1});if(!scheduleAt||scheduleAt<=new Date())await executeJob(req,job.toObject?job.toObject():job);req.flash?.('success',scheduleAt&&scheduleAt>new Date()?'Backup scheduled.':'Backup completed successfully.');}catch(err){req.flash?.('error',err.message||'Backup failed.');}return res.redirect('/admin/backups');},
 run:async(req,res)=>{try{const{BackupJob}=req.models;if(!oid(req.params.id))throw new Error('Invalid backup.');const job=await BackupJob.findOne({_id:req.params.id,isDeleted:{$ne:true},migrationQuarantinedAt:null}).lean();if(!job)throw new Error('Backup job not found.');await executeJob(req,job);req.flash?.('success','Backup completed successfully.');}catch(err){req.flash?.('error',err.message||'Backup failed.');}return res.redirect('/admin/backups');},
 download:async(req,res)=>{try{const{BackupJob}=req.models;if(!oid(req.params.id))return res.status(404).send('Not found');const job=await BackupJob.findOne({_id:req.params.id,status:'Completed',isDeleted:{$ne:true},migrationQuarantinedAt:null}).lean();if(!job)return res.status(404).send('Backup not found');const buf=await artifactBuffer(job);if(backup.sha256(buf)!==job.checksum)return res.status(409).send('Backup checksum verification failed.');res.setHeader('Content-Type','application/octet-stream');res.setHeader('Content-Disposition',`attachment; filename="${str(job.name,80).replace(/[^A-Za-z0-9._-]/g,'-')}.cakb"`);return res.send(buf);}catch(err){console.error('Backup download error:', err);return res.status(500).send('Download failed.');}},
 restore:async(req,res)=>{let source=null;try{const{BackupJob}=req.models;if(!oid(req.params.id))throw new Error('Invalid backup.');source=await BackupJob.findOne({_id:req.params.id,status:'Completed',isDeleted:{$ne:true},migrationQuarantinedAt:null}).lean();if(!source)throw new Error('Completed backup not found.');if(!backup.confirmationMatches(source.name,req.body.confirmation))throw new Error(`Type RESTORE ${source.name} to confirm.`);backup.parseKey();const claim=await BackupJob.updateOne({_id:source._id,status:'Completed',revision:Number(source.revision||1),$or:[{restoreLockUntil:null},{restoreLockUntil:{$lt:new Date()}}]},{$set:{status:'Restoring',restoreLockUntil:new Date(Date.now()+15*60*1000),updatedBy:actorId(req)},$inc:{revision:1}});if(!(claim.modifiedCount||claim.nModified))throw new Error('Restore is already running or this backup changed.');const safety=await BackupJob.create({name:`Pre-restore safety ${new Date().toISOString()}`,type:'Manual',scope:'Full System',storage:'Cloudinary',retentionDays:30,status:'Scheduled',notes:`Automatic safety backup before restoring ${source.name}`,createdBy:actorId(req),updatedBy:actorId(req),revision:1});await executeJob(req,safety.toObject?safety.toObject():safety);const buf=await artifactBuffer(source),payload=await backup.unpackAsync(buf,backup.parseKey(),source.checksum);const payloadCode=String(payload.tenant?.code||''),tenantCode=String(req.tenant?.code||''),payloadId=String(payload.tenant?.id||''),tenantId=String(req.tenant?._id||'');if((tenantCode&&payloadCode!==tenantCode)||(!tenantCode&&tenantId&&payloadId!==tenantId))throw new Error('Backup belongs to a different tenant.');const conn=BackupJob.db;await replaceFromPayload(req.models,payload,conn);await BackupJob.updateOne({_id:source._id,status:'Restoring'},{$set:{status:'Completed',restoreLockUntil:null,updatedBy:actorId(req)},$push:{restoreHistory:{actorUserId:actorId(req),actorName:actorName(req),scope:source.scope,status:'Completed',note:`Restored after safety backup ${safety._id}.`,createdAt:new Date()}},$inc:{revision:1}});req.flash?.('success','Backup restored successfully.');}catch(err){if(source?._id)await req.models.BackupJob.updateOne({_id:source._id,status:'Restoring'},{$set:{status:'Completed',restoreLockUntil:null},$push:{restoreHistory:{actorUserId:actorId(req),actorName:actorName(req),scope:source.scope,status:'Failed',note:str(err.message,500),createdAt:new Date()}},$inc:{revision:1}}).catch(()=>{});req.flash?.('error',err.message||'Restore failed.');}return res.redirect('/admin/backups');},
 archive:async(req,res)=>{try{const{BackupJob}=req.models;const job=await BackupJob.findOne({_id:req.params.id,isDeleted:{$ne:true}}).lean();if(!job)throw new Error('Backup not found.');if(['Running','Restoring'].includes(job.status))throw new Error('Running backup cannot be archived.');const r=await BackupJob.updateOne({_id:job._id,revision:Number(job.revision||1)},{$set:{status:'Archived',updatedBy:actorId(req)},$inc:{revision:1}});if(!(r.modifiedCount||r.nModified))throw new Error('Backup changed in another session.');req.flash?.('success','Backup archived.');}catch(err){req.flash?.('error',err.message);}return res.redirect('/admin/backups');},
 delete:async(req,res)=>{try{const{BackupJob}=req.models;const job=await BackupJob.findOne({_id:req.params.id,isDeleted:{$ne:true}}).lean();if(!job)throw new Error('Backup not found.');if(job.status!=='Archived')throw new Error('Archive the backup before deleting it.');const rev=Number(job.revision||1);const r=await BackupJob.updateOne({_id:job._id,revision:rev,status:'Archived'},{$set:{isDeleted:true,deletedAt:new Date(),updatedBy:actorId(req)},$inc:{revision:1}});if(!(r.modifiedCount||r.nModified))throw new Error('Backup changed in another session.');if(job.filePublicId){const destroyed=await safeDestroy(job.filePublicId,job.fileResourceType||'raw');if(!destroyed){await BackupJob.updateOne({_id:job._id,revision:rev+1,isDeleted:true},{$set:{isDeleted:false,deletedAt:null,updatedBy:actorId(req)},$inc:{revision:1}}).catch(()=>{});throw new Error('Backup storage deletion failed; archive was retained.');}}req.flash?.('success','Backup deleted.');}catch(err){req.flash?.('error',err.message);}return res.redirect('/admin/backups');},
 exportCsv:async(req,res)=>{const{BackupJob}=req.models;const ids=str(req.query.ids,10000).split(',').map(x=>x.trim()).filter(oid).slice(0,5000);const q={isDeleted:{$ne:true}};if(ids.length)q._id={$in:ids};const docs=await BackupJob.find(q).sort({createdAt:-1}).limit(5000).lean();const head=['Name','Type','Scope','Storage','Status','Size','Checksum','Scheduled','Completed','Created'];const lines=[head.map(csvCell).join(','),...docs.map(d=>[d.name,d.type,d.scope,d.storage,d.status,d.sizeLabel,d.checksum,fmt(d.scheduleAt),fmt(d.completedAt),fmt(d.createdAt)].map(csvCell).join(','))];res.setHeader('Content-Type','text/csv; charset=utf-8');res.setHeader('Content-Disposition','attachment; filename="backup-history.csv"');return res.send(lines.join('\n'));},
 bulkAction:async(req,res)=>{try{const{BackupJob}=req.models;const ids=str(req.body.ids,5000).split(',').map(x=>x.trim()).filter(oid).slice(0,10),action=str(req.body.action);if(!ids.length)throw new Error('Select backups first.');const jobs=await BackupJob.find({_id:{$in:ids},isDeleted:{$ne:true},migrationQuarantinedAt:null}).sort({_id:1}).lean();if(action==='run'){for(const j of jobs)await executeJob(req,j);}else if(action==='archive'){for(const j of jobs)if(['Running','Restoring'].includes(j.status))throw new Error(`${j.name} is running.`);const changed=[];try{for(const j of jobs){if(j.status==='Archived')continue;const rev=Number(j.revision||1),r=await BackupJob.updateOne({_id:j._id,revision:rev},{$set:{status:'Archived',updatedBy:actorId(req)},$inc:{revision:1}});if(!(r.modifiedCount||r.nModified))throw new Error(`${j.name} changed in another session.`);changed.push({id:j._id,status:j.status,revision:rev});}}catch(err){for(const c of changed.reverse())await BackupJob.updateOne({_id:c.id,revision:c.revision+1,status:'Archived'},{$set:{status:c.status,updatedBy:actorId(req)},$inc:{revision:1}}).catch(()=>{});throw err;}}else throw new Error('Invalid bulk action.');req.flash?.('success',`Bulk ${action} completed.`);}catch(err){req.flash?.('error',err.message||'Bulk action failed.');}return res.redirect('/admin/backups');}
};
module.exports.executeJob=executeJob;module.exports.createArtifact=createArtifact;
