const mongoose = require("mongoose");
const { body, validationResult } = require("express-validator");
const { normalizeCategory, inferCategory } = require("../../../services/tenant/notificationService");
function safeStr(v, def = "") { return v == null ? def : String(v); }
function isValidObjectId(id) { return mongoose.Types.ObjectId.isValid(String(id || "")); }
function escapeRegex(v) { return safeStr(v).replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); }
function normalizeType(v) { const x=safeStr(v,"info").trim().toLowerCase(); return ["info","success","warning","danger"].includes(x)?x:"info"; }
function normalizeAudience(v) { const x=safeStr(v,"admin").trim().toLowerCase(); return ["admin","staff","student","parent","all"].includes(x)?x:"admin"; }
function normalizeUrl(v) { const x=safeStr(v).trim(); if (!x) return ""; if (!x.startsWith("/") || x.startsWith("//") || /[\r\n]/.test(x)) throw new Error("Notification URL must be an internal portal path."); return x.slice(0,500); }
function parseDateValue(v) { if (!v) return null; const d=new Date(v); if(Number.isNaN(d.getTime())) throw new Error("Invalid notification date."); return d; }
function parseCsv(csvText) {
  const text=String(csvText||"").replace(/^\uFEFF/,""); const rows=[]; let row=[],current="",quotes=false;
  for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1]; if(ch==='"'){if(quotes&&next==='"'){current+='"';i++;}else quotes=!quotes;continue;} if(ch===','&&!quotes){row.push(current);current="";continue;} if((ch==='\n'||ch==='\r')&&!quotes){if(ch==='\r'&&next==='\n')i++;row.push(current);if(row.some(c=>String(c||"").trim()))rows.push(row);row=[];current="";continue;} current+=ch;}
  if(quotes) throw new Error("CSV contains an unclosed quoted field."); if(current.length||row.length){row.push(current);if(row.some(c=>String(c||"").trim()))rows.push(row);} return rows;
}
const notificationRules=[
  body("title").trim().isLength({min:2,max:140}).withMessage("Title is required (2-140 chars)."),
  body("message").trim().isLength({min:2,max:5000}).withMessage("Message is required (2-5000 chars)."),
  body("type").optional({checkFalsy:true}).isIn(["info","success","warning","danger"]).withMessage("Invalid type."),
  body("audience").optional({checkFalsy:true}).isIn(["admin","staff","student","parent","all"]).withMessage("Invalid audience."),
  body("category").optional({checkFalsy:true}).isIn(["general","academics","finance","admissions","events","library","hostel","transport","discipline","messages","system"]).withMessage("Invalid category."),
  body("url").optional({checkFalsy:true}).trim().isLength({max:500}).withMessage("URL is too long."),
  body("deliverAt").optional({checkFalsy:true}).isISO8601().withMessage("Invalid delivery date."),
  body("expiresAt").optional({checkFalsy:true}).isISO8601().withMessage("Invalid expiry date."),
];
function activeFilter(){const now=new Date();return{isDeleted:{$ne:true},$and:[{$or:[{deliverAt:null},{deliverAt:{$exists:false}},{deliverAt:{$lte:now}}]},{$or:[{expiresAt:null},{expiresAt:{$exists:false}},{expiresAt:{$gt:now}}]}]};}
function adminItem(row){return{...row,category:inferCategory(row),isRead:!!row.adminReviewedAt,readAt:row.adminReviewedAt||null};}
module.exports={
  notificationRules,
  page:async(req,res)=>{try{
    const {Notification}=req.models; const page=Math.max(parseInt(req.query.page||"1",10),1),limit=20; const q=safeStr(req.query.q).trim(),status=safeStr(req.query.status).trim().toLowerCase(),type=safeStr(req.query.type).trim().toLowerCase(),audience=safeStr(req.query.audience).trim().toLowerCase();
    const query=activeFilter(); if(q){const rx=new RegExp(escapeRegex(q),"i");query.$and.push({$or:[{title:rx},{message:rx},{entityType:rx}]});} if(status==="read")query.adminReviewedAt={$ne:null}; if(status==="unread")query.$or=[{adminReviewedAt:null},{adminReviewedAt:{$exists:false}}]; if(["info","success","warning","danger"].includes(type))query.type=type; if(["admin","staff","student","parent","all"].includes(audience))query.audience=audience;
    const base=activeFilter(); const [total,reviewRows]=await Promise.all([Notification.countDocuments(query),Notification.aggregate([{$match:base},{$group:{_id:{$cond:[{$ne:["$adminReviewedAt",null]},"read","unread"]},count:{$sum:1}}}])]); const pages=Math.max(Math.ceil(total/limit),1),safePage=Math.min(page,pages); const raw=await Notification.find(query).sort({createdAt:-1,_id:-1}).skip((safePage-1)*limit).limit(limit).lean(); const reviewCounts=Object.fromEntries(reviewRows.map((row)=>[String(row._id||""),Number(row.count||0)])),unreviewed=reviewCounts.unread||0,reviewed=reviewCounts.read||0;
    return res.render("tenant/notifications/index",{tenant:req.tenant||null,csrfToken:res.locals.csrfToken||(req.csrfToken?req.csrfToken():""),items:raw.map(adminItem),filters:{q,status,type,audience},pagination:{page:safePage,pages,total,limit},kpis:{total,unread:unreviewed,read:reviewed,scheduledLive:total},messages:{success:req.flash?req.flash("success"):[],error:req.flash?req.flash("error"):[]}});
  }catch(err){console.error("NOTIFICATIONS PAGE ERROR:",err);req.flash?.("error","Failed to load notifications.");return res.status(500).redirect("/admin/notifications");}},
  create:async(req,res)=>{try{const {Notification}=req.models;const errors=validationResult(req);if(!errors.isEmpty())throw new Error(errors.array().map(e=>e.msg).join(" ")); const title=safeStr(req.body.title).trim().slice(0,140),message=safeStr(req.body.message).trim().slice(0,5000),type=normalizeType(req.body.type),audience=normalizeAudience(req.body.audience),category=normalizeCategory(req.body.category),url=normalizeUrl(req.body.url),deliverAt=parseDateValue(req.body.deliverAt),expiresAt=parseDateValue(req.body.expiresAt);if(!title||!message)throw new Error("Title and message are required.");if(deliverAt&&expiresAt&&expiresAt<=deliverAt)throw new Error("Expiry date must be after delivery date.");await Notification.create({title,message,type,audience,category,url,deliverAt,expiresAt,isRead:false,readAt:null,adminReviewedAt:null,createdBy:req.user?._id||null,updatedBy:req.user?._id||null});req.flash?.("success","Notification created.");}catch(err){req.flash?.("error",err.message||"Failed to create notification.");}return res.redirect("/admin/notifications");},
  importCsv:async(req,res)=>{try{const {Notification}=req.models;if(!req.file?.buffer)throw new Error("CSV file is required.");const rows=parseCsv(req.file.buffer.toString("utf8"));if(rows.length<2)throw new Error("CSV file is empty or invalid.");if(rows.length>2000)throw new Error("CSV import is limited to 1,999 data rows.");const headers=rows[0].map(h=>safeStr(h).trim());const map=Object.fromEntries(headers.map((h,i)=>[h,i]));for(const h of ["title","message","type","audience","url","deliverAt","expiresAt"])if(!(h in map))throw new Error("Invalid CSV headers. Required: title,message,type,audience,url,deliverAt,expiresAt; category is optional.");const docs=[];for(let i=1;i<rows.length;i++){const row=rows[i],title=safeStr(row[map.title]).trim().slice(0,140),message=safeStr(row[map.message]).trim().slice(0,5000);if(!title||!message)throw new Error(`Row ${i+1}: title and message are required.`);const deliverAt=parseDateValue(row[map.deliverAt]),expiresAt=parseDateValue(row[map.expiresAt]);if(deliverAt&&expiresAt&&expiresAt<=deliverAt)throw new Error(`Row ${i+1}: expiry must be after delivery.`);docs.push({title,message,type:normalizeType(row[map.type]),audience:normalizeAudience(row[map.audience]),category:normalizeCategory(map.category==null?"general":row[map.category]),url:normalizeUrl(row[map.url]),deliverAt,expiresAt,isRead:false,readAt:null,adminReviewedAt:null,createdBy:req.user?._id||null,updatedBy:req.user?._id||null});}await Notification.insertMany(docs,{ordered:true});req.flash?.("success",`${docs.length} notification(s) imported.`);}catch(err){req.flash?.("error",err.message||"Failed to import CSV.");}return res.redirect("/admin/notifications");},
  markRead:async(req,res)=>{const id=safeStr(req.params.id);if(isValidObjectId(id))await req.models.Notification.updateOne({_id:id,isDeleted:{$ne:true}},{$set:{adminReviewedAt:new Date(),adminReviewedBy:req.user?._id||null,updatedBy:req.user?._id||null}});return res.redirect("/admin/notifications");},
  markUnread:async(req,res)=>{const id=safeStr(req.params.id);if(isValidObjectId(id))await req.models.Notification.updateOne({_id:id,isDeleted:{$ne:true}},{$set:{adminReviewedAt:null,adminReviewedBy:null,updatedBy:req.user?._id||null}});return res.redirect("/admin/notifications");},
  deleteOne:async(req,res)=>{const id=safeStr(req.params.id);if(isValidObjectId(id))await req.models.Notification.updateOne({_id:id,isDeleted:{$ne:true}},{$set:{isDeleted:true,deletedAt:new Date(),updatedBy:req.user?._id||null}});return res.redirect("/admin/notifications");},
  bulk:async(req,res)=>{try{const action=safeStr(req.body.action).toLowerCase(),raw=Array.isArray(req.body.ids)?req.body.ids:safeStr(req.body.ids).split(","),ids=raw.map(x=>safeStr(x)).filter(isValidObjectId);if(!ids.length)throw new Error("No notifications selected.");let set;if(action==="read")set={adminReviewedAt:new Date(),adminReviewedBy:req.user?._id||null,updatedBy:req.user?._id||null};else if(action==="unread")set={adminReviewedAt:null,adminReviewedBy:null,updatedBy:req.user?._id||null};else if(action==="delete")set={isDeleted:true,deletedAt:new Date(),updatedBy:req.user?._id||null};else throw new Error("Invalid bulk action.");await req.models.Notification.updateMany({_id:{$in:ids},isDeleted:{$ne:true}},{$set:set});}catch(err){req.flash?.("error",err.message);}return res.redirect("/admin/notifications");},
  markAllRead:async(req,res)=>{await req.models.Notification.updateMany(activeFilter(),{$set:{adminReviewedAt:new Date(),adminReviewedBy:req.user?._id||null,updatedBy:req.user?._id||null}});return res.redirect("/admin/notifications");},
};
