const { getParent } = require("./_helpers");
const { loadPortalNotifications, markPortalNotificationRead, markAllPortalNotificationsRead, getPreference, savePreference, CATEGORY_FIELDS, portalNotificationFilter, directNotificationOwnershipFilter } = require("../../../services/tenant/notificationService");
// Keep the underlying visibility/ownership contracts explicit for audits while receipt state is applied by loadPortalNotifications.
void portalNotificationFilter;
void directNotificationOwnershipFilter;
function fmtDate(v){if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleString();}
function preferenceInput(body={}){const out={inApp:body.inApp==="on"||body.inApp==="true"||body.inApp===true};CATEGORY_FIELDS.forEach(k=>{out[k]=k==="system"?true:(body[k]==="on"||body[k]==="true"||body[k]===true);});return out;}
function normalizeNotification(row={}){const body=row.body||row.message||row.content||"";return{...row,title:row.title||row.subject||"Notification",body,excerpt:body.length>160?`${body.slice(0,160)}...`:body,type:String(row.type||row.category||"general").toLowerCase(),read:!!row.effectiveRead,createdLabel:fmtDate(row.createdAt||row.sentAt||row.date),readLabel:row.effectiveReadAt?fmtDate(row.effectiveReadAt):null,actionUrl:row.url||row.actionUrl||row.link||null,actionLabel:row.actionLabel||row.linkLabel||"Open"};}
module.exports={
  async index(req,res){try{const {user,parent}=await getParent(req);if(!user)return res.redirect("/login");const [rawRows,preference]=await Promise.all([loadPortalNotifications(req.models,user,["parent"],{limit:200}),getPreference(req.models,user)]);const rows=rawRows.map(normalizeNotification),types=[...new Set(rows.map(r=>String(r.type||"").trim()).filter(Boolean))],unread=rows.filter(r=>!r.read).length;return res.render("parents/notifications",{tenant:req.tenant,user,parent,notifications:rows,preference,preferenceCategories:CATEGORY_FIELDS,stats:{total:rows.length,unread,read:rows.length-unread},filters:{status:String(req.query?.status||"").trim(),type:String(req.query?.type||"").trim(),q:String(req.query?.q||"").trim()},options:{types},error:null});}catch(err){console.error("PARENT NOTIFICATIONS ERROR:",err);return res.status(500).send("Failed to load parent notifications page");}},
  async markRead(req,res){try{const {user}=await getParent(req);if(user)await markPortalNotificationRead(req.models,user,String(req.params?.id||""),["parent"]);}catch{}return res.redirect("/parent/notifications");},
  async markAllRead(req,res){try{const {user}=await getParent(req);if(user)await markAllPortalNotificationsRead(req.models,user,["parent"]);}catch{}return res.redirect("/parent/notifications");},
  async savePreferences(req,res){try{const {user}=await getParent(req);if(!user)return res.redirect("/login");await savePreference(req.models,user,preferenceInput(req.body));req.flash?.("success","Notification preferences updated.");}catch(err){req.flash?.("error",err.message||"Could not update preferences.");}return res.redirect("/parent/notifications");},
};
