const crypto=require('crypto');
const str=(v,max=200)=>String(v==null?'':v).trim().replace(/\s+/g,' ').slice(0,max);
const idText=(v)=>String(v?._id||v||'');
function csvCell(v){let s=String(v==null?'':v);if(/^[=+\-@\t\r]/.test(s))s=`'${s}`;return `"${s.replace(/"/g,'""')}"`;}
function activeAssignments(asset){return (asset?.assignments||[]).filter(a=>a.status==='Assigned'&&!a.returnedAt);}
function assignedQuantity(asset){return activeAssignments(asset).reduce((n,a)=>n+Math.max(1,Number(a.quantity||1)),0);}
function assertAssetEditable(asset){if(!asset||asset.isDeleted===true)throw new Error('Asset was not found.');if(asset.status==='Disposed')throw new Error('Disposed assets are immutable.');}
function buildAssetValues({input={},current=null,actorId=null}){if(current)assertAssetEditable(current);const quantity=Math.max(1,Math.floor(Number(input.quantity??current?.quantity??1)||1));const used=assignedQuantity(current);if(quantity<used)throw new Error('Asset quantity cannot be lower than the quantity currently assigned.');const values={assetTag:str(input.assetTag??current?.assetTag,80).toUpperCase(),name:str(input.name??current?.name,160),category:str(input.category??current?.category,40)||'Other',brand:str(input.brand??current?.brand,100),model:str(input.model??current?.model,100),serialNumber:str(input.serialNumber??current?.serialNumber,120),quantity,unitCost:Math.max(0,Number(input.unitCost??current?.unitCost??0)||0),purchaseDate:input.purchaseDate?new Date(input.purchaseDate):(current?.purchaseDate||null),supplier:str(input.supplier??current?.supplier,160),location:str(input.location??current?.location,160),condition:str(input.condition??current?.condition,20)||'Good',notes:str(input.notes??current?.notes,1000),revision:Number(current?.revision||0)+1,updatedBy:actorId||null};if(!values.assetTag||!values.name)throw new Error('Asset tag and asset name are required.');if(!current){values.createdBy=actorId||null;values.status='Available';}return values;}
function assertAssignmentAllowed(asset,quantity=1){assertAssetEditable(asset);if(asset.status==='Maintenance')throw new Error('Assets under maintenance cannot be assigned.');const q=Math.max(1,Math.floor(Number(quantity)||1));const free=Math.max(0,Number(asset.quantity||1)-assignedQuantity(asset));if(q>free)throw new Error('Assignment exceeds available asset quantity.');return q;}
function newMovement(type,actorName,note,actorId=null,now=new Date()){return{type,actorName:str(actorName,120),actorId:actorId||null,note:str(note,500),date:now};}
function newAssignment({assignedTo,assigneeType='Other',assigneeId=null,quantity=1,dueBackAt=null,note='',actorId=null,now=new Date()}){const type=str(assigneeType,20)||'Other';if(!['Staff','Department','Office','Student','Other'].includes(type))throw new Error('Invalid asset assignee type.');if(['Student','Staff'].includes(type)&&!assigneeId)throw new Error(`${type} assignments require a canonical profile.`);return{assignedTo:str(assignedTo,160),assigneeType:type,assigneeId:assigneeId||null,quantity:Math.max(1,Math.floor(Number(quantity)||1)),assignedAt:now,dueBackAt:dueBackAt?new Date(dueBackAt):null,status:'Assigned',returnedAt:null,returnedBy:null,note:str(note,500),updatedBy:actorId||null};}
function deriveAssetStatus(asset,{openMaintenance=false}={}){if(asset.disposedAt)return'Disposed';if(openMaintenance)return'Maintenance';return assignedQuantity(asset)>0?'Assigned':'Available';}
function assertReturnAllowed(asset,assignment){assertAssetEditable(asset);if(!assignment||assignment.status!=='Assigned'||assignment.returnedAt)throw new Error('Only an active assignment can be returned.');return true;}
function assertMaintenanceOpenAllowed(asset){assertAssetEditable(asset);if(assignedQuantity(asset)>0)throw new Error('Return all assigned units before opening maintenance.');return true;}
function assertDisposeAllowed(asset,{openMaintenance=false}={}){assertAssetEditable(asset);if(assignedQuantity(asset)>0)throw new Error('Return all assigned units before disposal.');if(openMaintenance)throw new Error('Resolve open maintenance before disposal.');return true;}
function newTicketCode(now=new Date()){return `MT-${now.toISOString().slice(0,10).replace(/-/g,'')}-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;}
function maintenanceValues({asset,input={},actorId=null,current=null,now=new Date()}){if(!current)assertMaintenanceOpenAllowed(asset);const status=str(input.status??current?.status,20).toLowerCase()||'open';if(!['open','in_progress','resolved','cancelled'].includes(status))throw new Error('Invalid maintenance status.');if(current&&['resolved','cancelled'].includes(current.status)&&status!==current.status)throw new Error('Closed maintenance tickets are immutable.');const values={asset:asset._id||asset,title:str(input.title??current?.title,160),description:str(input.description??current?.description,600),priority:str(input.priority??current?.priority,20).toLowerCase()||'normal',status,cost:Math.max(0,Number(input.cost??current?.cost??0)||0),vendor:str(input.vendor??current?.vendor,120),resolution:str(input.resolution??current?.resolution,600),revision:Number(current?.revision||0)+1,updatedBy:actorId||null};if(!values.title)throw new Error('Maintenance title is required.');if(!['low','normal','high','urgent'].includes(values.priority))throw new Error('Invalid maintenance priority.');if(!current){values.ticketCode=newTicketCode(now);values.openedAt=now;values.createdBy=actorId||null;}else values.ticketCode=current.ticketCode;if(['resolved','cancelled'].includes(status)){values.closedAt=current?.closedAt||now;values.closedBy=actorId||null;}return values;}
module.exports={str,idText,csvCell,activeAssignments,assignedQuantity,assertAssetEditable,buildAssetValues,assertAssignmentAllowed,newMovement,newAssignment,deriveAssetStatus,assertReturnAllowed,assertMaintenanceOpenAllowed,assertDisposeAllowed,newTicketCode,maintenanceValues};
