const crypto=require('crypto');const zlib=require('zlib');
const EXCLUDED=new Set(['BackupJob','AuditLog','ReportExport','SystemHealth','InviteToken','TimetableMutationLock']);
const CONFIG=new Set(['Setting','TenantProfile','FeeStructure','StaffRole','AdmissionRequirement','Intake','Class','Section','Stream','Subject','Classroom']);
function str(v,max=500){return String(v??'').trim().slice(0,max);}
function parseKey(raw=process.env.TENANT_BACKUP_KEY||''){const s=String(raw||'').trim();let b=null;if(/^[a-f\d]{64}$/i.test(s))b=Buffer.from(s,'hex');else{try{b=Buffer.from(s,'base64')}catch{}}if(!b||b.length!==32)throw new Error('TENANT_BACKUP_KEY must be a 32-byte base64 or 64-character hex key.');return b;}
function sha256(v){return crypto.createHash('sha256').update(v).digest('hex');}
function encrypt(buffer,key){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),body=Buffer.concat([cipher.update(buffer),cipher.final()]),tag=cipher.getAuthTag();return Buffer.concat([Buffer.from('CAKB1'),iv,tag,body]);}
function decrypt(buffer,key){if(!Buffer.isBuffer(buffer)||buffer.slice(0,5).toString()!=='CAKB1')throw new Error('Backup artifact format is invalid.');const iv=buffer.subarray(5,17),tag=buffer.subarray(17,33),body=buffer.subarray(33),dec=crypto.createDecipheriv('aes-256-gcm',key,iv);dec.setAuthTag(tag);return Buffer.concat([dec.update(body),dec.final()]);}
function modelNames(models,scope='Full System'){const all=Object.keys(models||{}).filter(n=>!EXCLUDED.has(n));if(scope==='Config Only')return all.filter(n=>CONFIG.has(n));if(scope==='Full System')return all;throw new Error('Unsupported backup scope.');}
async function snapshot(models,{scope='Full System',tenant=null,now=new Date(),maxDocuments=250000}={}){const names=modelNames(models,scope),collections={},manifest=[];let total=0;for(const name of names){const M=models[name];if(!M||typeof M.find!=='function')continue;const count=typeof M.countDocuments==='function'?await M.countDocuments({}):null;if(Number.isFinite(count)&&total+count>maxDocuments)throw new Error(`Backup exceeds ${maxDocuments} document safety limit.`);const docs=await M.find({}).lean();total+=docs.length;if(total>maxDocuments)throw new Error(`Backup exceeds ${maxDocuments} document safety limit.`);collections[name]=docs;manifest.push({model:name,count:docs.length});}return {format:'classic-academy-backup',version:1,createdAt:now.toISOString(),tenant:{id:String(tenant?._id||''),code:str(tenant?.code,80),name:str(tenant?.name,180)},scope,manifest,collections};}
function pack(payload,key=parseKey(),maxPlainBytes=200*1024*1024){const plain=Buffer.from(JSON.stringify(payload),'utf8');if(plain.length>maxPlainBytes)throw new Error('Backup payload exceeds 200 MB safety limit.');const compressed=zlib.gzipSync(plain,{level:9});const encrypted=encrypt(compressed,key);return {buffer:encrypted,checksum:sha256(encrypted),plainHash:sha256(plain),plainBytes:plain.length,compressedBytes:compressed.length};}
function unpack(buffer,key=parseKey(),expectedChecksum='',maxPlainBytes=200*1024*1024){if(expectedChecksum&&sha256(buffer)!==expectedChecksum)throw new Error('Backup checksum verification failed.');const compressed=decrypt(buffer,key);const plain=zlib.gunzipSync(compressed,{maxOutputLength:maxPlainBytes});const payload=JSON.parse(plain.toString('utf8'));if(payload?.format!=='classic-academy-backup'||payload?.version!==1||!payload.collections||!Array.isArray(payload.manifest))throw new Error('Backup manifest is invalid.');return payload;}
function confirmationMatches(name,value){return str(value,300)===`RESTORE ${str(name,220)}`;}
function sizeLabel(bytes){const n=Number(bytes||0);if(n<1024)return `${n} B`;if(n<1024*1024)return `${(n/1024).toFixed(2)} KB`;if(n<1024*1024*1024)return `${(n/1024/1024).toFixed(2)} MB`;return `${(n/1024/1024/1024).toFixed(2)} GB`;}
async function validatePayloadForModels(payload,models){if(!payload||!['Full System','Config Only'].includes(payload.scope))throw new Error('Backup scope is invalid.');const expected=modelNames(models,payload.scope).filter((name)=>models[name]&&typeof models[name].find==='function').sort();const names=[];for(const row of payload.manifest){const name=str(row?.model,120);if(!name||names.includes(name))throw new Error('Backup manifest contains duplicate or invalid model entries.');if(!models[name]||typeof models[name].find!=='function')throw new Error(`Backup model ${name} is not available in this tenant runtime.`);const docs=payload.collections[name];if(!Array.isArray(docs)||docs.length!==Number(row.count))throw new Error(`Backup manifest count mismatch for ${name}.`);names.push(name);}names.sort();if(names.length!==expected.length||names.some((n,i)=>n!==expected[i]))throw new Error('Backup manifest does not match the expected model scope.');const extras=Object.keys(payload.collections||{}).filter((n)=>!names.includes(n));if(extras.length)throw new Error('Backup contains collections outside its manifest.');return true;}
module.exports={EXCLUDED,CONFIG,str,parseKey,sha256,encrypt,decrypt,modelNames,snapshot,pack,unpack,confirmationMatches,sizeLabel,validatePayloadForModels};
