const crypto=require('crypto');const zlib=require('zlib');const {promisify}=require('util');
const gzipAsyncNative=promisify(zlib.gzip),gunzipAsyncNative=promisify(zlib.gunzip);
const EXCLUDED=new Set(['BackupJob','AuditLog','ReportExport','SystemHealth','InviteToken','TimetableMutationLock']);
const CONFIG=new Set(['Setting','TenantProfile','FeeStructure','StaffRole','AdmissionRequirement','Intake','Class','Section','Stream','Subject','Classroom']);
function str(v,max=500){return String(v??'').trim().slice(0,max);}
function parseKey(raw=process.env.TENANT_BACKUP_KEY||''){const s=String(raw||'').trim();let b=null;if(/^[a-f\d]{64}$/i.test(s))b=Buffer.from(s,'hex');else{try{b=Buffer.from(s,'base64')}catch{}}if(!b||b.length!==32)throw new Error('TENANT_BACKUP_KEY must be a 32-byte base64 or 64-character hex key.');return b;}
function sha256(v){return crypto.createHash('sha256').update(v).digest('hex');}
function encrypt(buffer,key){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),body=Buffer.concat([cipher.update(buffer),cipher.final()]),tag=cipher.getAuthTag();return Buffer.concat([Buffer.from('CAKB1'),iv,tag,body]);}
function decrypt(buffer,key){if(!Buffer.isBuffer(buffer)||buffer.slice(0,5).toString()!=='CAKB1')throw new Error('Backup artifact format is invalid.');const iv=buffer.subarray(5,17),tag=buffer.subarray(17,33),body=buffer.subarray(33),dec=crypto.createDecipheriv('aes-256-gcm',key,iv);dec.setAuthTag(tag);return Buffer.concat([dec.update(body),dec.final()]);}
function modelNames(models,scope='Full System'){const all=Object.keys(models||{}).filter(n=>!EXCLUDED.has(n));if(scope==='Config Only')return all.filter(n=>CONFIG.has(n));if(scope==='Full System')return all;throw new Error('Unsupported backup scope.');}
async function runBounded(items,limit,worker){const rows=new Array(items.length),workers=[];let next=0;const count=Math.max(1,Math.min(Number(limit)||1,items.length||1));for(let i=0;i<count;i++)workers.push((async()=>{while(true){const idx=next++;if(idx>=items.length)return;rows[idx]=await worker(items[idx],idx);}})());await Promise.all(workers);return rows;}
function backupQueryConcurrency(){const n=Number(process.env.BACKUP_QUERY_CONCURRENCY||3);return Number.isFinite(n)?Math.max(1,Math.min(6,Math.floor(n))):3;}
function backupGzipLevel(){const n=Number(process.env.BACKUP_GZIP_LEVEL||6);return Number.isFinite(n)?Math.max(1,Math.min(9,Math.floor(n))):6;}
async function snapshot(models,{scope='Full System',tenant=null,now=new Date(),maxDocuments=250000}={}){const names=modelNames(models,scope).filter(name=>models[name]&&typeof models[name].find==='function');const concurrency=backupQueryConcurrency();const counts=await runBounded(names,concurrency,async(name)=>{const M=models[name];return typeof M.countDocuments==='function'?await M.countDocuments({}):null;});const knownTotal=counts.reduce((sum,n)=>sum+(Number.isFinite(n)?n:0),0);if(knownTotal>maxDocuments)throw new Error(`Backup exceeds ${maxDocuments} document safety limit.`);const rows=await runBounded(names,concurrency,async(name)=>{const docs=await models[name].find({}).lean();return{name,docs};});const collections={},manifest=[];let total=0;for(const row of rows){total+=row.docs.length;if(total>maxDocuments)throw new Error(`Backup exceeds ${maxDocuments} document safety limit.`);collections[row.name]=row.docs;manifest.push({model:row.name,count:row.docs.length});}return {format:'classic-academy-backup',version:1,createdAt:now.toISOString(),tenant:{id:String(tenant?._id||''),code:str(tenant?.code,80),name:str(tenant?.name,180)},scope,manifest,collections};}
function encodePlain(payload,maxPlainBytes){const plain=Buffer.from(JSON.stringify(payload),'utf8');if(plain.length>maxPlainBytes)throw new Error('Backup payload exceeds 200 MB safety limit.');return plain;}
function validateUnpackedPayload(plain){const payload=JSON.parse(plain.toString('utf8'));if(payload?.format!=='classic-academy-backup'||payload?.version!==1||!payload.collections||!Array.isArray(payload.manifest))throw new Error('Backup manifest is invalid.');return payload;}
function pack(payload,key=parseKey(),maxPlainBytes=200*1024*1024){const plain=encodePlain(payload,maxPlainBytes);const compressed=zlib.gzipSync(plain,{level:backupGzipLevel()});const encrypted=encrypt(compressed,key);return {buffer:encrypted,checksum:sha256(encrypted),plainHash:sha256(plain),plainBytes:plain.length,compressedBytes:compressed.length};}
async function packAsync(payload,key=parseKey(),maxPlainBytes=200*1024*1024){const plain=encodePlain(payload,maxPlainBytes);const compressed=await gzipAsyncNative(plain,{level:backupGzipLevel()});const encrypted=encrypt(compressed,key);return {buffer:encrypted,checksum:sha256(encrypted),plainHash:sha256(plain),plainBytes:plain.length,compressedBytes:compressed.length};}
function unpack(buffer,key=parseKey(),expectedChecksum='',maxPlainBytes=200*1024*1024){if(expectedChecksum&&sha256(buffer)!==expectedChecksum)throw new Error('Backup checksum verification failed.');const compressed=decrypt(buffer,key);const plain=zlib.gunzipSync(compressed,{maxOutputLength:maxPlainBytes});return validateUnpackedPayload(plain);}
async function unpackAsync(buffer,key=parseKey(),expectedChecksum='',maxPlainBytes=200*1024*1024){if(expectedChecksum&&sha256(buffer)!==expectedChecksum)throw new Error('Backup checksum verification failed.');const compressed=decrypt(buffer,key);const plain=await gunzipAsyncNative(compressed,{maxOutputLength:maxPlainBytes});return validateUnpackedPayload(plain);}
function confirmationMatches(name,value){return str(value,300)===`RESTORE ${str(name,220)}`;}
function sizeLabel(bytes){const n=Number(bytes||0);if(n<1024)return `${n} B`;if(n<1024*1024)return `${(n/1024).toFixed(2)} KB`;if(n<1024*1024*1024)return `${(n/1024/1024).toFixed(2)} MB`;return `${(n/1024/1024/1024).toFixed(2)} GB`;}
async function validatePayloadForModels(payload,models){if(!payload||!['Full System','Config Only'].includes(payload.scope))throw new Error('Backup scope is invalid.');const expected=modelNames(models,payload.scope).filter((name)=>models[name]&&typeof models[name].find==='function').sort();const names=[];for(const row of payload.manifest){const name=str(row?.model,120);if(!name||names.includes(name))throw new Error('Backup manifest contains duplicate or invalid model entries.');if(!models[name]||typeof models[name].find!=='function')throw new Error(`Backup model ${name} is not available in this tenant runtime.`);const docs=payload.collections[name];if(!Array.isArray(docs)||docs.length!==Number(row.count))throw new Error(`Backup manifest count mismatch for ${name}.`);names.push(name);}names.sort();if(names.length!==expected.length||names.some((n,i)=>n!==expected[i]))throw new Error('Backup manifest does not match the expected model scope.');const extras=Object.keys(payload.collections||{}).filter((n)=>!names.includes(n));if(extras.length)throw new Error('Backup contains collections outside its manifest.');return true;}
module.exports={EXCLUDED,CONFIG,str,parseKey,sha256,encrypt,decrypt,modelNames,snapshot,pack,packAsync,unpack,unpackAsync,backupQueryConcurrency,backupGzipLevel,confirmationMatches,sizeLabel,validatePayloadForModels};
