const crypto=require("crypto");
const CASE_STATUSES=new Set(["open","investigating","hearing","resolved","dismissed"]);
const str=(v,max=1500)=>String(v??"").trim().replace(/\s+/g," ").slice(0,max);
const idText=(v)=>!v?"":String(typeof v==="object"&&v._id?v._id:v);
function escapeRegExp(value){return String(value||"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&");}
function csvCell(value){let text=String(value??"");if(/^[\s]*[=+\-@]/.test(text))text=`'${text}`;return `"${text.replace(/"/g,'""')}"`;}
function normalizeCaseStatus(value,fallback="open"){const s=str(value,30).toLowerCase();if(!s)return fallback;if(!CASE_STATUSES.has(s))throw new Error("Invalid discipline status.");return s;}
function newCaseNumber(now=new Date()){const day=now.toISOString().slice(0,10).replace(/-/g,"");return `DC-${day}-${crypto.randomBytes(4).toString("hex").toUpperCase()}`;}
function assertStudentEligible(student){const status=str(student?.status,30).toLowerCase();if(!student||student.isDeleted===true||["archived","graduated"].includes(status))throw new Error("Discipline cases require a current student record.");return true;}
function assertTransition(current,nextStatus,{reopen=false}={}){const from=normalizeCaseStatus(current?.status||"open"),to=normalizeCaseStatus(nextStatus,from);if(["resolved","dismissed"].includes(from)&&!reopen)throw new Error("Closed discipline cases must be explicitly reopened before further changes.");if(reopen&&!["resolved","dismissed"].includes(from))throw new Error("Only closed discipline cases can be reopened.");return to;}
function buildCaseValues({student,input={},current=null,actorId=null,now=new Date(),reopen=false}){assertStudentEligible(student);const incidentDate=new Date(input.incidentDate);if(Number.isNaN(incidentDate.getTime()))throw new Error("Incident date is required.");const category=str(input.category,80),description=str(input.description,1500);if(!category||!description)throw new Error("Category and description are required.");const status=current?assertTransition(current,input.status||current.status,{reopen}):normalizeCaseStatus(input.status||"open");const values={student:student._id||student.id,studentRegNo:str(student.regNo,60),studentName:str(student.fullName||[student.firstName,student.lastName].filter(Boolean).join(" "),120),classId:str(student.classId,80),className:str(student.className,180),academicYear:str(student.academicYear,20),term:Number(student.term||0)||null,incidentDate,category,description,status,note:str(input.note,800),studentVisible:input.studentVisible===true||String(input.studentVisible)==="true"||String(input.studentVisible)==="1",parentVisible:input.parentVisible===true||String(input.parentVisible)==="true"||String(input.parentVisible)==="1",updatedBy:actorId||null,revision:current?Math.max(0,Number(current.revision||0))+1:0};if(!current)values.createdBy=actorId||null;if(["resolved","dismissed"].includes(status)&&(!current||current.status!==status)){values.resolutionSummary=str(input.resolutionSummary||input.note,1200);values.resolvedAt=now;values.resolvedBy=actorId||null;}if(reopen){values.reopenedAt=now;values.reopenedBy=actorId||null;values.resolvedAt=null;values.resolvedBy=null;}return values;}
function assertDeleteAllowed(row={}){if(normalizeCaseStatus(row.status||"open")!=="open"||row.publishedAt||row.studentVisible||row.parentVisible||(row.actions||[]).length||row.studentStatement||(row.attachments||[]).length)throw new Error("Only unpublished open discipline cases with no evidence or actions can be removed.");return true;}
function safeEvidenceFile(file,{maxBytes=10*1024*1024}={}){if(!file?.buffer)throw new Error("Choose a file.");if(Number(file.size||file.buffer.length)>maxBytes)throw new Error("File is too large.");const mime=str(file.mimetype,100).toLowerCase();if(!/^(application\/pdf|image\/(jpeg|png|webp))$/.test(mime))throw new Error("Only PDF, JPEG, PNG or WEBP files are allowed.");return true;}
function disciplineVisibilityFilterForStudent(studentId,{parent=false}={}){return {student:studentId,isDeleted:{ $ne:true },migrationQuarantinedAt:null,[parent?"parentVisible":"studentVisible"]:true};}
function safeCaseSummary(row={}, { parent=false } = {}){const visibilityKey=parent?"visibleToParent":"visibleToStudent";return {_id:row._id,caseNo:row.caseNo||"",incidentDate:row.incidentDate||null,category:row.category||"",status:row.status||"open",description:row.description||"",resolutionSummary:row.resolutionSummary||"",actions:(row.actions||[]).filter(a=>a?.[visibilityKey]===true).map(a=>({action:a.action||"",details:a.details||"",date:a.date||null}))};}
async function retireDisciplineNotifications(models,caseId,actorId=null){const {Notification}=models||{};if(!Notification||!caseId)return 0;const r=await Notification.updateMany({entityType:"discipline_case",entityId:caseId,isDeleted:{ $ne:true }},{ $set:{isDeleted:true,deletedAt:new Date(),updatedBy:actorId||null} });return r.modifiedCount||0;}
async function syncDisciplineNotifications(models,row,student,actorId=null){const {Notification}=models||{};if(!Notification||!row?._id)return 0;await retireDisciplineNotifications(models,row._id,actorId);const targets=[];if(row.studentVisible&&student?.userId)targets.push({audience:"student",userId:student.userId,url:"/student/discipline"});if(row.parentVisible&&student?.guardianUserId)targets.push({audience:"parent",userId:student.guardianUserId,url:"/parent/discipline?student="+encodeURIComponent(String(student._id))});for(const t of targets)await Notification.create({audience:t.audience,userId:t.userId,title:`Discipline case ${row.caseNo}`,message:`${row.category}: ${row.status}`,type:["resolved","dismissed"].includes(row.status)?"info":"warning",url:t.url,entityType:"discipline_case",entityId:row._id,entityAction:"visible_update",createdBy:actorId||null});return targets.length;}
module.exports={normalizeCaseStatus,newCaseNumber,assertStudentEligible,assertTransition,buildCaseValues,assertDeleteAllowed,safeEvidenceFile,disciplineVisibilityFilterForStudent,safeCaseSummary,retireDisciplineNotifications,syncDisciplineNotifications,escapeRegExp,csvCell};
