const str=(v,max=200)=>String(v==null?'':v).trim().replace(/\s+/g,' ').slice(0,max);
function code(v){return str(v,40).toUpperCase().replace(/[^A-Z0-9-]+/g,'-').replace(/-{2,}/g,'-').replace(/(^-|-$)/g,'');}
function roomKey(v){return str(v,120).toLowerCase();}
function normalizeStatus(v,fallback='available'){const x=str(v,20).toLowerCase()||fallback;if(!['available','maintenance','inactive','archived'].includes(x))throw new Error('Invalid classroom status.');return x;}
function assertTransition(current,next){const from=normalizeStatus(current?.status||'available'),to=normalizeStatus(next,from);if(from==='archived'&&to!=='archived')throw new Error('Archived classrooms are immutable.');return to;}
function buildClassroomValues({input={},current=null,actorId=null,now=new Date()}){const status=current?assertTransition(current,input.status||current.status):normalizeStatus(input.status,'available');const name=str(input.name??current?.name,120),roomCode=code(input.code??current?.code??name);const capacity=Math.floor(Number(input.capacity??current?.capacity??0));if(!name||!roomCode)throw new Error('Classroom name and code are required.');if(!Number.isInteger(capacity)||capacity<1)throw new Error('Classroom capacity must be at least 1.');const values={name,code:roomCode,roomKey:roomKey(input.roomKey??current?.roomKey??name),capacity,type:str(input.type??current?.type,20).toLowerCase()||'lecture',campus:str(input.campus??current?.campus,120),building:str(input.building??current?.building,120),floor:str(input.floor??current?.floor,60),location:str(input.location??current?.location,180),status,notes:str(input.notes??current?.notes,600),maintenanceReason:str(input.maintenanceReason??current?.maintenanceReason,300),maintenanceUntil:input.maintenanceUntil?new Date(input.maintenanceUntil):(current?.maintenanceUntil||null),revision:Number(current?.revision||0)+1,updatedBy:actorId||null};if(!['lecture','lab','tutorial','hall','office','other'].includes(values.type))throw new Error('Invalid classroom type.');if(status==='maintenance'&&!values.maintenanceReason)throw new Error('Maintenance reason is required.');if(status!=='maintenance'){values.maintenanceReason='';values.maintenanceUntil=null;}if(!current)values.createdBy=actorId||null;if(status==='archived')values.archivedAt=current?.archivedAt||now;else if(current?.archivedAt)values.archivedAt=current.archivedAt;return values;}
function activeTimetableFilter(classroom){return{status:'active',migrationQuarantinedAt:null,roomKey:roomKey(classroom?.roomKey||classroom?.name)};}
function assertStatusChangeAllowed(current,nextStatus,activeScheduleCount=0){const next=assertTransition(current,nextStatus);if(['maintenance','inactive','archived'].includes(next)&&Number(activeScheduleCount||0)>0)throw new Error('This classroom is used by published timetable entries. Reschedule or unpublish them first.');return next;}
function assertRoomSchedulable(classroom){if(classroom&&classroom.status!=='available')throw new Error('The selected classroom is not available for published timetable use.');return true;}
module.exports={str,code,roomKey,normalizeStatus,assertTransition,buildClassroomValues,activeTimetableFilter,assertStatusChangeAllowed,assertRoomSchedulable};
