const DOC_STATUSES=new Set(["pending","verified","rejected","expired"]);
const str=(v,max=800)=>String(v??"").trim().replace(/\s+/g," ").slice(0,max);
function normalizeDocumentStatus(value,fallback="pending"){const s=str(value,30).toLowerCase();if(!s)return fallback;if(!DOC_STATUSES.has(s))throw new Error("Invalid document status.");return s;}
function safeDocumentFile(file,{maxBytes=10*1024*1024}={}){if(!file?.buffer)throw new Error("Choose a document file.");if(Number(file.size||file.buffer.length)>maxBytes)throw new Error("Document file is too large.");const mime=str(file.mimetype,100).toLowerCase();if(!/^(application\/pdf|image\/(jpeg|png|webp))$/.test(mime))throw new Error("Only PDF, JPEG, PNG or WEBP documents are allowed.");return true;}
function safeStoredUrl(value){const raw=str(value,1200);try{const u=new URL(raw);return ["http:","https:"].includes(u.protocol)?u.toString():"";}catch{return "";}}
function parseDateOnly(value,field){if(!value)return null;const raw=str(value,20);if(!/^\d{4}-\d{2}-\d{2}$/.test(raw))throw new Error(`${field} must be YYYY-MM-DD.`);const d=new Date(`${raw}T00:00:00.000Z`);if(Number.isNaN(d.getTime()))throw new Error(`${field} is invalid.`);return d;}
function effectiveDocumentStatus(row={},now=new Date()){if(row.isDeleted===true)return "deleted";if(row.expiryDate&&new Date(row.expiryDate).getTime()<new Date(now).getTime())return "expired";return normalizeDocumentStatus(row.status||"pending");}
function buildDocumentLifecycleValues({current={},input={},actorId=null,now=new Date(),fileReplaced=false}){let status=normalizeDocumentStatus(input.status||current.status||"pending");const issueDate=parseDateOnly(input.issueDate,"Issue date"),expiryDate=parseDateOnly(input.expiryDate,"Expiry date");if(issueDate&&expiryDate&&expiryDate<issueDate)throw new Error("Expiry date cannot be before issue date.");if(fileReplaced)status="pending";const values={status,issueDate,expiryDate,studentVisible:input.studentVisible==null?(current.studentVisible!==false):[true,"true","1",1].includes(input.studentVisible),parentVisible:input.parentVisible==null?(current.parentVisible!==false):[true,"true","1",1].includes(input.parentVisible),updatedBy:actorId||null,revision:Math.max(0,Number(current.revision||0))+(current._id?1:0)};if(status==="verified"){values.verifiedAt=now;values.verifiedBy=actorId||null;values.rejectionReason="";}else if(status==="rejected"){const reason=str(input.rejectionReason,500);if(!reason)throw new Error("Rejection reason is required.");values.rejectionReason=reason;values.verifiedAt=null;values.verifiedBy=null;}else{values.rejectionReason="";if(fileReplaced){values.verifiedAt=null;values.verifiedBy=null;}}return values;}
function studentDocumentFilter(studentId,{parent=false}={}){return {student:studentId,isDeleted:{ $ne:true },migrationQuarantinedAt:null,[parent?"parentVisible":"studentVisible"]:true};}
function canDestroyStoredAsset(row={}){return !!(row.doc?.publicId&&!row.doc?.sharedAsset);}
function csvCell(value){let text=String(value??"");if(/^[\s]*[=+\-@]/.test(text))text=`'${text}`;return `"${text.replace(/"/g,'""')}"`;}
module.exports={normalizeDocumentStatus,safeDocumentFile,safeStoredUrl,parseDateOnly,effectiveDocumentStatus,buildDocumentLifecycleValues,studentDocumentFilter,canDestroyStoredAsset,csvCell};
